local procedural_basements = {

  --  basement1 = { width=20, height=20, stairx=3, stairy=9, stairDir="N" },
--    basement2 = { width=20, height=20, stairx=2, stairy=5, stairDir="N" }, -- Lemmy's multi-story basement, is 10x10 chunk size
--	basement_10x10_1story_NEstairsN = { width=11, height=11, stairx=9, stairy=1, stairDir="N" },
--	basement_10x10_1story_NWstairsN = { width=11, height=11, stairx=0, stairy=1, stairDir="N" },
--	basement_10x10_1story_SEstairsN = { width=11, height=11, stairx=9, stairy=6, stairDir="N" },
--	basement_10x10_1story_SWstairsN = { width=11, height=11, stairx=0, stairy=6, stairDir="N" },
--	basement_7x7_1story_SWstairsN = { width=8, height=8, stairx=0, stairy=3, stairDir="N" },
--	basement_7x7_1story_SstairsW = { width=8, height=8, stairx=2, stairy=6, stairDir="W" },
--	basement_7x7_1story_WstairsN = { width=8, height=8, stairx=0, stairy=2, stairDir="N" },

    -- This text is created by TileZed when exporting the .pzby files.
    -- The commented-out ones are unique basements placed as lots in WorldEd; they won't spawn randomly.

--    lot_basement_apartmentbuilding_28 = { width=71, height=11, stairx=0, stairy=2, stairDir="N" },
--    lot_basement_bank_02 = { width=11, height=14, stairx=5, stairy=12, stairDir="W" },
--    lot_basement_bank_03_riverwood = { width=13, height=12, stairx=1, stairy=10, stairDir="W" },
--    lot_basement_bank_10 = { width=16, height=8, stairx=2, stairy=6, stairDir="W" },
    lot_basement_bar_01_wooden = { width=13, height=13, stairx=1, stairy=0, stairDir="W" },
--    lot_basement_bar_18_music = { width=9, height=14, stairx=0, stairy=8, stairDir="N" },
--    lot_basement_bar_19_smutz = { width=12, height=15, stairx=1, stairy=0, stairDir="W" },
--    lot_basement_bar_rusty_rifle = { width=9, height=7, stairx=7, stairy=1, stairDir="N" },
--    lot_basement_buildingdestroyed_02 = { width=13, height=10, stairx=6, stairy=8, stairDir="W" },
--    lot_basement_church_27_ekron = { width=28, height=30, stairx=25, stairy=12, stairDir="N" },
--    lot_basement_church_30 = { width=17, height=13, stairx=7, stairy=11, stairDir="W" },
--    lot_basement_coldwar_bunker_01 = { width=61, height=52, stairx=0, stairy=24, stairDir="N" },
--    lot_basement_construction_01_factory = { width=37, height=33, stairx=10, stairy=0, stairDir="W" },
--    lot_basement_detentioncenter_01 = { width=40, height=43, stairx=37, stairy=1, stairDir="N" },
--    lot_basement_example_for_guide = { width=6, height=10, stairx=0, stairy=1, stairDir="N" },
--    lot_basement_factory_19_abandoned = { width=10, height=18, stairx=8, stairy=3, stairDir="N" },
--    lot_basement_factory_27_abandoned = { width=18, height=86, stairx=0, stairy=5, stairDir="W" },
--    lot_basement_farmhouse_01_E = { width=11, height=18, stairx=4, stairy=8, stairDir="W" },
--    lot_basement_farmhouse_ekron = { width=15, height=13, stairx=0, stairy=0, stairDir="W" },
--    lot_basement_farmhouse_ekron_2 = { width=10, height=9, stairx=0, stairy=0, stairDir="W" },
--    lot_basement_firestation_05 = { width=17, height=24, stairx=0, stairy=18, stairDir="N" },
--    lot_basement_gas_07_generic = { width=8, height=16, stairx=2, stairy=14, stairDir="W" },
--    lot_basement_gas_15_brandenburg = { width=10, height=10, stairx=0, stairy=1, stairDir="N" },
--    lot_basement_gas_18_bigspring = { width=17, height=8, stairx=13, stairy=2, stairDir="N" },
--    lot_basement_gas_19_rural = { width=16, height=16, stairx=8, stairy=3, stairDir="N" },
--    lot_basement_generalstore_01 = { width=17, height=12, stairx=12, stairy=10, stairDir="W" },
--    lot_basement_government_06_secret = { width=179, height=109, stairx=22, stairy=57, stairDir="W" },
--    lot_basement_gunclub_01 = { width=21, height=7, stairx=19, stairy=1, stairDir="N" },
    lot_basement_house_01 = { width=6, height=10, stairx=0, stairy=1, stairDir="N" },
    lot_basement_house_02 = { width=6, height=10, stairx=0, stairy=1, stairDir="N" },
    lot_basement_house_03 = { width=10, height=10, stairx=0, stairy=1, stairDir="N" },
    lot_basement_house_04 = { width=10, height=12, stairx=2, stairy=1, stairDir="N" },
    lot_basement_house_05 = { width=13, height=15, stairx=5, stairy=1, stairDir="N" },
    lot_basement_house_06 = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_B = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_B_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_C = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_C_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_D = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_D_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_E = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_E_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_F = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_F_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_G = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_G_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_H = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_H_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_I = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_I_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_J = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_J_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_K = { width=12, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_06_K_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_06_east = { width=13, height=12, stairx=4, stairy=10, stairDir="W" },
    lot_basement_house_07 = { width=5, height=5, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_07_B = { width=5, height=5, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_07_B_east = { width=5, height=5, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_07_C = { width=5, height=5, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_07_C_east = { width=5, height=5, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_07_D = { width=5, height=5, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_07_D_east = { width=5, height=5, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_07_east = { width=5, height=5, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_07_empty = { width=5, height=5, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_07_empty_east = { width=5, height=5, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_08 = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_B = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_B_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_C = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_C_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_D = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_D_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_E = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_E_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_F = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_F_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_G = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_empty = { width=10, height=11, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_08_empty_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_08_south = { width=11, height=10, stairx=9, stairy=0, stairDir="N" },
    lot_basement_house_09 = { width=14, height=13, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_09_east = { width=13, height=14, stairx=4, stairy=12, stairDir="W" },
    lot_basement_house_10 = { width=10, height=10, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_10_B = { width=10, height=10, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_10_B_east = { width=10, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_10_east = { width=10, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_11 = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_B = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_B_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_C = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_C_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_D = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_D_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_E = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_E_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_F = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_F_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_G = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_G_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_empty = { width=8, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_11_empty_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_11_south = { width=12, height=8, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_12 = { width=11, height=9, stairx=2, stairy=0, stairDir="W" },
    lot_basement_house_12_south = { width=9, height=11, stairx=7, stairy=2, stairDir="N" },
    lot_basement_house_13 = { width=6, height=13, stairx=0, stairy=11, stairDir="W" },
    lot_basement_house_13_south = { width=13, height=6, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_14 = { width=12, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_14_B = { width=12, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_14_B_south = { width=8, height=12, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_14_empty = { width=12, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_14_empty_south = { width=8, height=12, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_14_south = { width=8, height=12, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_15 = { width=11, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_15_south = { width=10, height=11, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_16 = { width=8, height=11, stairx=0, stairy=2, stairDir="N" },
    lot_basement_house_16_B = { width=8, height=11, stairx=0, stairy=2, stairDir="N" },
    lot_basement_house_16_B_east = { width=11, height=8, stairx=2, stairy=6, stairDir="W" },
    lot_basement_house_16_east = { width=11, height=8, stairx=2, stairy=6, stairDir="W" },
    lot_basement_house_17 = { width=8, height=12, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_17_B = { width=8, height=12, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_17_B_east = { width=12, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_17_east = { width=12, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_17_empty = { width=8, height=12, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_17_empty_east = { width=12, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_18 = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_18_B = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_18_B_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_18_C = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_18_C_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_18_D = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_18_D_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_18_E = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_18_E_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_18_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_19 = { width=10, height=12, stairx=0, stairy=2, stairDir="W" },
    lot_basement_house_19_south = { width=12, height=10, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_20 = { width=6, height=8, stairx=0, stairy=3, stairDir="N" },
    lot_basement_house_20_east = { width=8, height=6, stairx=3, stairy=4, stairDir="W" },
    lot_basement_house_20_empty = { width=6, height=8, stairx=0, stairy=3, stairDir="N" },
    lot_basement_house_20_empty_east = { width=8, height=6, stairx=3, stairy=4, stairDir="W" },
    lot_basement_house_21 = { width=6, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_21_south = { width=7, height=6, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_22 = { width=7, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_22_east = { width=8, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_23 = { width=7, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_23_B = { width=7, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_23_B_east = { width=8, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_23_C = { width=7, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_23_C_east = { width=8, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_23_D = { width=7, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_23_D_east = { width=8, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_23_east = { width=8, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_24 = { width=5, height=7, stairx=0, stairy=2, stairDir="N" },
    lot_basement_house_24_east = { width=7, height=5, stairx=2, stairy=3, stairDir="W" },
    lot_basement_house_25 = { width=14, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_25_empty = { width=14, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_25_empty_south = { width=8, height=14, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_25_south = { width=8, height=14, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_26 = { width=11, height=14, stairx=0, stairy=4, stairDir="W" },
    lot_basement_house_26_south = { width=14, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_27 = { width=11, height=10, stairx=4, stairy=4, stairDir="W" },
    lot_basement_house_27_south = { width=10, height=11, stairx=4, stairy=4, stairDir="N" },
    lot_basement_house_28 = { width=11, height=9, stairx=5, stairy=7, stairDir="W" },
    lot_basement_house_28_south = { width=9, height=11, stairx=0, stairy=5, stairDir="N" },
    lot_basement_house_29 = { width=7, height=13, stairx=0, stairy=10, stairDir="W" },
    lot_basement_house_29_south = { width=13, height=7, stairx=1, stairy=0, stairDir="N" },
    lot_basement_house_30 = { width=9, height=10, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_30_B = { width=9, height=10, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_30_B_east = { width=10, height=9, stairx=0, stairy=7, stairDir="W" },
    lot_basement_house_30_B_empty = { width=9, height=10, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_30_B_empty_east = { width=10, height=9, stairx=0, stairy=7, stairDir="W" },
    lot_basement_house_30_east = { width=10, height=9, stairx=0, stairy=7, stairDir="W" },
    lot_basement_house_31 = { width=10, height=14, stairx=0, stairy=8, stairDir="N" },
    lot_basement_house_31_B = { width=10, height=14, stairx=0, stairy=8, stairDir="N" },
    lot_basement_house_31_B_east = { width=14, height=10, stairx=8, stairy=8, stairDir="W" },
    lot_basement_house_31_east = { width=14, height=10, stairx=8, stairy=8, stairDir="W" },
    lot_basement_house_32 = { width=7, height=15, stairx=5, stairy=0, stairDir="N" },
    lot_basement_house_32_east = { width=15, height=7, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_33 = { width=16, height=18, stairx=13, stairy=13, stairDir="N" },
    lot_basement_house_34 = { width=7, height=5, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_34_south = { width=5, height=7, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_35 = { width=13, height=15, stairx=9, stairy=10, stairDir="N" },
    lot_basement_house_35_B = { width=8, height=5, stairx=4, stairy=0, stairDir="N" },
    lot_basement_house_35_B_east = { width=5, height=8, stairx=0, stairy=2, stairDir="W" },
    lot_basement_house_35_east = { width=15, height=13, stairx=10, stairy=2, stairDir="W" },
    lot_basement_house_36 = { width=9, height=9, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_36_south = { width=9, height=9, stairx=7, stairy=0, stairDir="N" },
    lot_basement_house_37 = { width=9, height=10, stairx=0, stairy=4, stairDir="W" },
    lot_basement_house_37_empty = { width=9, height=10, stairx=0, stairy=4, stairDir="W" },
    lot_basement_house_37_empty_south = { width=10, height=9, stairx=4, stairy=0, stairDir="N" },
    lot_basement_house_37_south = { width=10, height=9, stairx=4, stairy=0, stairDir="N" },
    lot_basement_house_38 = { width=12, height=7, stairx=6, stairy=5, stairDir="W" },
    lot_basement_house_38_B = { width=7, height=7, stairx=1, stairy=5, stairDir="W" },
    lot_basement_house_38_B_south = { width=7, height=6, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_38_south = { width=7, height=12, stairx=0, stairy=6, stairDir="N" },
    lot_basement_house_39 = { width=10, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_39_B = { width=10, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_39_B_south = { width=10, height=10, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_39_south = { width=10, height=10, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_40 = { width=10, height=8, stairx=4, stairy=0, stairDir="W" },
    lot_basement_house_40_south = { width=8, height=10, stairx=6, stairy=4, stairDir="N" },
    lot_basement_house_41 = { width=10, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_41_B = { width=10, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_41_B_east = { width=8, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_41_B_empty = { width=10, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_41_B_empty_east = { width=8, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_41_east = { width=8, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_42 = { width=10, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_42_B = { width=10, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_42_B_south = { width=8, height=10, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_42_C = { width=10, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_42_C_south = { width=8, height=10, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_42_empty = { width=10, height=8, stairx=4, stairy=6, stairDir="W" },
    lot_basement_house_42_empty_south = { width=8, height=10, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_42_south = { width=8, height=10, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_43 = { width=16, height=14, stairx=11, stairy=0, stairDir="N" },
    lot_basement_house_44 = { width=11, height=9, stairx=6, stairy=0, stairDir="N" },
    lot_basement_house_44_east = { width=9, height=11, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_45 = { width=14, height=9, stairx=4, stairy=0, stairDir="N" },
    lot_basement_house_45_east = { width=9, height=14, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_46 = { width=11, height=11, stairx=5, stairy=0, stairDir="N" },
    lot_basement_house_46_east = { width=11, height=11, stairx=0, stairy=4, stairDir="W" },
    lot_basement_house_47 = { width=7, height=11, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_47_east = { width=11, height=7, stairx=0, stairy=5, stairDir="W" },
    lot_basement_house_48 = { width=8, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_48_empty = { width=8, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_48_empty_south = { width=10, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_48_south = { width=10, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_49 = { width=9, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_49_east = { width=9, height=9, stairx=0, stairy=7, stairDir="W" },
    lot_basement_house_50 = { width=7, height=8, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_50_south = { width=8, height=7, stairx=6, stairy=0, stairDir="N" },
    lot_basement_house_51 = { width=10, height=9, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_51_B = { width=10, height=9, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_51_B_south = { width=9, height=10, stairx=7, stairy=0, stairDir="N" },
    lot_basement_house_51_C = { width=10, height=9, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_51_C_south = { width=9, height=10, stairx=7, stairy=0, stairDir="N" },
    lot_basement_house_51_south = { width=9, height=10, stairx=7, stairy=0, stairDir="N" },
    lot_basement_house_52 = { width=11, height=9, stairx=1, stairy=7, stairDir="W" },
    lot_basement_house_52_south = { width=9, height=11, stairx=0, stairy=1, stairDir="N" },
    lot_basement_house_53 = { width=11, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_53_south = { width=10, height=11, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_54 = { width=11, height=11, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_54_east = { width=11, height=11, stairx=4, stairy=9, stairDir="W" },
    lot_basement_house_55 = { width=7, height=10, stairx=0, stairy=4, stairDir="N" },
    lot_basement_house_55_east = { width=10, height=7, stairx=4, stairy=5, stairDir="W" },
    lot_basement_house_56 = { width=10, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_56_east = { width=9, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_56_empty = { width=10, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_56_empty_east = { width=9, height=10, stairx=0, stairy=8, stairDir="W" },
    lot_basement_house_57 = { width=9, height=14, stairx=1, stairy=0, stairDir="W" },
    lot_basement_house_57_south = { width=14, height=9, stairx=12, stairy=1, stairDir="N" },
    lot_basement_house_58 = { width=8, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_58_east = { width=9, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_58_empty = { width=8, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_58_empty_east = { width=9, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_59 = { width=10, height=9, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_59_east = { width=9, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_60 = { width=12, height=10, stairx=4, stairy=0, stairDir="W" },
    lot_basement_house_60_empty = { width=12, height=10, stairx=4, stairy=0, stairDir="W" },
    lot_basement_house_60_empty_south = { width=10, height=12, stairx=8, stairy=4, stairDir="N" },
    lot_basement_house_60_south = { width=10, height=12, stairx=8, stairy=4, stairDir="N" },
    lot_basement_house_61 = { width=8, height=13, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_61_east = { width=13, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_61_empty = { width=8, height=13, stairx=3, stairy=0, stairDir="N" },
    lot_basement_house_61_empty_east = { width=13, height=8, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_62 = { width=8, height=11, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_62_B = { width=8, height=11, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_62_B_east = { width=11, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_62_C = { width=8, height=11, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_62_C_east = { width=11, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_62_east = { width=11, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_63 = { width=8, height=9, stairx=0, stairy=7, stairDir="W" },
    lot_basement_house_63_south = { width=9, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_64 = { width=10, height=8, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_64_east = { width=8, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_65 = { width=10, height=13, stairx=3, stairy=4, stairDir="N" },
    lot_basement_house_65_east = { width=13, height=10, stairx=4, stairy=5, stairDir="W" },
    lot_basement_house_66 = { width=8, height=8, stairx=0, stairy=6, stairDir="W" },
    lot_basement_house_66_south = { width=8, height=8, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_67 = { width=10, height=10, stairx=8, stairy=0, stairDir="N" },
    lot_basement_house_67_east = { width=10, height=10, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_68 = { width=12, height=7, stairx=10, stairy=0, stairDir="N" },
    lot_basement_house_68_east = { width=7, height=12, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_69 = { width=21, height=19, stairx=0, stairy=3, stairDir="W" },
    lot_basement_house_E2_01 = { width=9, height=5, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_E2_02 = { width=9, height=7, stairx=0, stairy=1, stairDir="W" },
    lot_basement_house_E2_03 = { width=9, height=10, stairx=0, stairy=1, stairDir="W" },
    lot_basement_house_E2_04 = { width=9, height=7, stairx=0, stairy=0, stairDir="W" },
    lot_basement_house_E2_05 = { width=10, height=13, stairx=3, stairy=1, stairDir="W" },
    lot_basement_house_E_01 = { width=10, height=6, stairx=1, stairy=0, stairDir="W" },
    lot_basement_house_E_02 = { width=10, height=6, stairx=1, stairy=0, stairDir="W" },
    lot_basement_house_E_03 = { width=10, height=10, stairx=1, stairy=0, stairDir="W" },
    lot_basement_house_E_04 = { width=11, height=11, stairx=1, stairy=4, stairDir="W" },
    lot_basement_house_E_05 = { width=15, height=12, stairx=4, stairy=3, stairDir="W" },
    lot_basement_house_S2_01 = { width=8, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_S2_02 = { width=8, height=9, stairx=0, stairy=0, stairDir="N" },
    lot_basement_house_S2_03 = { width=14, height=14, stairx=4, stairy=5, stairDir="N" },
    lot_basement_house_easteregg_spiffo = { width=14, height=14, stairx=0, stairy=1, stairDir="N" },
--    lot_basement_house_kingofthehill_dale = { width=15, height=10, stairx=7, stairy=1, stairDir="N" },
    lot_basement_house_medium_38_westpoint = { width=10, height=10, stairx=5, stairy=0, stairDir="W" },
    lot_basement_house_small_03_westpoint = { width=10, height=7, stairx=8, stairy=2, stairDir="N" },
    lot_basement_house_small_103_v38_westpoint = { width=10, height=7, stairx=8, stairy=2, stairDir="N" },
--    lot_basement_house_wadsworth_main = { width=13, height=16, stairx=7, stairy=6, stairDir="N" },
--    lot_basement_jamieton_bunker_01 = { width=4, height=14, stairx=2, stairy=9, stairDir="N" },
--    lot_basement_offices_03_building = { width=24, height=21, stairx=13, stairy=2, stairDir="N" },
--    lot_basement_offices_39_egg = { width=19, height=13, stairx=13, stairy=5, stairDir="W" },
--    lot_basement_paddlewheeler = { width=32, height=10, stairx=27, stairy=8, stairDir="W" },
--    lot_basement_plaza_09_westpoint = { width=13, height=28, stairx=3, stairy=15, stairDir="W" },
--    lot_basement_plaza_19_legal = { width=16, height=32, stairx=0, stairy=12, stairDir="N" },
--    lot_basement_plaza_20_legal = { width=16, height=38, stairx=1, stairy=13, stairDir="W" },
--    lot_basement_plaza_25_riverwood = { width=15, height=24, stairx=1, stairy=7, stairDir="W" },
--    lot_basement_police_02_westpoint = { width=13, height=19, stairx=6, stairy=12, stairDir="N" },
--    lot_basement_police_muldraugh = { width=21, height=21, stairx=14, stairy=19, stairDir="W" },
--    lot_basement_prison_01 = { width=58, height=33, stairx=0, stairy=0, stairDir="W" },
--    lot_basement_restaurant_64_firehall = { width=14, height=9, stairx=7, stairy=4, stairDir="N" },
--    lot_basement_sanatorium_tunnel = { width=8, height=216, stairx=5, stairy=0, stairDir="N" },
--    lot_basement_school_06 = { width=23, height=15, stairx=11, stairy=5, stairDir="W" },
--    lot_basement_school_25 = { width=26, height=42, stairx=23, stairy=21, stairDir="N" },
--    lot_basement_school_27_irvington = { width=17, height=27, stairx=7, stairy=0, stairDir="N" },
--    lot_basement_storefront_09 = { width=15, height=9, stairx=13, stairy=4, stairDir="N" },
--    lot_basement_storefront_13 = { width=8, height=14, stairx=2, stairy=0, stairDir="W" },
--    lot_basement_storefront_15 = { width=26, height=10, stairx=2, stairy=0, stairDir="W" },

	basement_parking1 = { width = 50, height = 50, stairx=-1, stairy=-1, stairDir="" },
}

-- Basement spawn locations are usually specified in WorldEd.
-- The table below can be used to specify additional basement spawn locations.
local procedural_basement_spawn_locations = {
--    {x=12024, y=2598, stairDir="N", choices={"lot_basement_house_06"}},
--    {x=12024, y=2598, z=-1, stairDir="N", choices={"lot_basement_house_06"}},
--    {x=12616, y=2425, stairDir="", choices={"basement_parking1"}},
--    {x=12025, y=2600, stairDir="W", choices={"lot_basement_house_51"}},
}

-- These .pzby files are used to modify the map near the staircase leading down to a basement.
-- For example, these can be used to replace a wall with a doorframe + door in a particular building.
local procedural_basement_access = {
    ba_exterior_1 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_north_eastside_01 = { width=2, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_eastside_02 = { width=2, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_eastside_02_C = { width=2, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_eastside_03_C = { width=2, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_eastside_04 = { width=2, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_01 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_02 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_03 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_04 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_05 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_06 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_07 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_08 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_09 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_10 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_11 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_12 = { width=1, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_13 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_14 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_15 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_16 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_17 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_18 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_19 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_20 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_21 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_22 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_23 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_24 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_25 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_26 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_27 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_28 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_29 = { width=1, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_30 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_31 = { width=1, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_32 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_33 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_34 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_35 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_36 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_37 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_38 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_39 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_40 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_41 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_north_westside_42 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_exterior_west_northside_01 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_02 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_03 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_04 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_05 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_06 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_07 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_08 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_09 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_10 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_11 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_12 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_13 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_14 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_15 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_16 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_17 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_northside_18 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_01 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_01_C = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_02_C = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_03 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_03_C = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_03_D = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_04_C = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_exterior_west_southside_05_C = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_country_02_E_01 = { width=3, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_house_country_04_S_01 = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_country_04_W_01 = { width=6, height=2, stairx=2, stairy=0, stairDir="W" },
    ba_house_lake_05_east = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_large_01_E_03 = { width=1, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_E_03B = { width=1, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_E_06 = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_large_01_E_07 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_E_08 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_E_09 = { width=5, height=1, stairx=1, stairy=-1, stairDir="W" },
    ba_house_large_01_E_09B = { width=1, height=1, stairx=1, stairy=-1, stairDir="W" },
    ba_house_large_01_N_02 = { width=1, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_N_05 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_N_08 = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_large_01_S_01 = { width=1, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_S_02 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_large_01_S_05 = { width=6, height=2, stairx=2, stairy=0, stairDir="W" },
    ba_house_large_01_S_07 = { width=2, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_house_large_01_S_08 = { width=1, height=5, stairx=0, stairy=1, stairDir="N" },
    ba_house_large_01_W_01 = { width=2, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_large_01_W_05 = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_medium_07 = { width=1, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_medium_100_E = { width=1, height=4, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_100_N = { width=4, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_medium_100_S = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_medium_11 = { width=1, height=1, stairx=-1, stairy=1, stairDir="N" },
    ba_house_medium_13 = { width=1, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_18_farmhouse = { width=2, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_22_redbrick = { width=1, height=1, stairx=-1, stairy=1, stairDir="N" },
    ba_house_medium_22_redbrick_var_m = { width=1, height=1, stairx=-1, stairy=1, stairDir="N" },
    ba_house_medium_27_redbrick = { width=1, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_29_farmhouse = { width=2, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_35_farmhouse = { width=2, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_38 = { width=1, height=1, stairx=-1, stairy=1, stairDir="N" },
    ba_house_medium_41 = { width=1, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_42 = { width=1, height=2, stairx=0, stairy=2, stairDir="N" },
    ba_house_medium_43 = { width=2, height=1, stairx=1, stairy=1, stairDir="N" },
    ba_house_medium_44_2 = { width=1, height=4, stairx=0, stairy=0, stairDir="N" },
    ba_house_medium_47_41v = { width=1, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_medium_92_farmhouse = { width=1, height=1, stairx=1, stairy=-1, stairDir="W" },
    ba_house_medium_93_farmhouse = { width=2, height=1, stairx=0, stairy=1, stairDir="N" },
    ba_house_medium_96_farmhouse = { width=2, height=2, stairx=1, stairy=1, stairDir="N" },
    ba_house_medium_96c_farmhouse = { width=1, height=1, stairx=2, stairy=-1, stairDir="W" },
    ba_house_medium_96d_farmhouse = { width=1, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_small_140_136v = { width=2, height=6, stairx=0, stairy=2, stairDir="N" },
    ba_house_small_173 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_small_44 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_small_98_interior = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_suburb_01_E_05 = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_house_suburb_01_E_05_01 = { width=5, height=1, stairx=1, stairy=0, stairDir="W" },
    ba_house_suburb_01_E_05_interior = { width=5, height=2, stairx=1, stairy=0, stairDir="W" },
    ba_interior_north_01 = { width=2, height=4, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_02 = { width=1, height=3, stairx=-1, stairy=0, stairDir="N" },
    ba_interior_north_03 = { width=1, height=4, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_04 = { width=1, height=3, stairx=-1, stairy=0, stairDir="N" },
    ba_interior_north_05 = { width=1, height=4, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_06 = { width=1, height=3, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_07 = { width=1, height=3, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_08 = { width=1, height=3, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_09 = { width=1, height=3, stairx=-1, stairy=0, stairDir="N" },
    ba_interior_north_10 = { width=1, height=3, stairx=-1, stairy=0, stairDir="N" },
    ba_interior_north_11 = { width=1, height=3, stairx=0, stairy=0, stairDir="N" },
    ba_interior_north_12 = { width=1, height=4, stairx=-1, stairy=0, stairDir="N" },
    ba_interior_west_01 = { width=3, height=1, stairx=0, stairy=-1, stairDir="W" },
    ba_interior_west_02 = { width=3, height=1, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_03 = { width=4, height=1, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_04 = { width=4, height=1, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_05 = { width=4, height=2, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_06 = { width=3, height=1, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_07 = { width=4, height=2, stairx=0, stairy=0, stairDir="W" },
    ba_interior_west_08 = { width=4, height=1, stairx=0, stairy=-1, stairDir="W" },
    ba_interior_west_09 = { width=4, height=1, stairx=0, stairy=0, stairDir="W" },
    ba_knoxhouse90_interior = { width=2, height=5, stairx=0, stairy=1, stairDir="N" },
}

local api = Basements.getAPIv1()
api:addAccessDefinitions('Muldraugh, KY', procedural_basement_access)
api:addBasementDefinitions('Muldraugh, KY', procedural_basements)
api:addSpawnLocations('Muldraugh, KY', procedural_basement_spawn_locations)
