-- require "Advanced_trajectory_core"
-- local HasEnterFireModeFlag = HasEnterFireModeFlag or false
-- local function HasGrenadelauncher(playerObj)
--     local MainGun = playerObj:getPrimaryHandItem()
--     if not MainGun then
--         return {false, false}
--     end
--     if MainGun:IsWeapon() and MainGun:isRanged() then
--         if MainGun:getStool() and MainGun:getStool():getType() == "M203_cat" then
--             return {true, true}
--         end
--         if MainGun:getStool() and MainGun:getStool():getType() == "M203_cat_empty" then
--             return {true, false}
--         end
--     end
--     return {false, false}
-- end
-- local function SetLauncherStatus(playerObj, type)
--     local MainGun = playerObj:getPrimaryHandItem()
--     if type == "Empty" then
--         local MagPart = instanceItem("Gunpart.M203_cat_empty")
--         MainGun:setWeaponPart("Stool", MagPart)
--     end
-- end
-- -- FlagNow 0 为有无武器  1 为是否装弹
-- local function CheckGrenadelauncher(playerObj)
--     local FlagNow = HasGrenadelauncher(playerObj)
--     if FlagNow[1] and playerObj:isAiming() then
--         local weaitem = instanceItem("Base.PipeBomb")
--         if Advanced_trajectory.GrenadeAimCursor == nil then
--             Advanced_trajectory.GrenadeAimCursor = ISShootGrenade:new("", "", playerObj, weaitem)
--             getCell():setDrag(Advanced_trajectory.GrenadeAimCursor, 0)
--         end
--         HasEnterFireModeFlag = true
--         return
--     end
--     if HasEnterFireModeFlag and not playerObj:isAiming() then
--         local DragNow = getCell():getDrag(0)
--         if DragNow and DragNow.Type == "ISShootGrenade" then
--             getCell():setDrag(nil, 0)
--         end
--         Advanced_trajectory.GrenadeAimCursor = nil
--         HasEnterFireModeFlag = false
--     end
-- end
-- local function LaunchGrenadeLauncher(_key)
--     if _key == getCore():getKey("LauchGrenadelauncherat") then
--         local playerObj = getPlayer()
--         local FlagNow = HasGrenadelauncher(playerObj)
--         if FlagNow[1] and playerObj:isAiming() then
--             if FlagNow[2] then
--                 local cell = getCell():getDrag(0)
--                 if cell == nil then
--                     return
--                 end
--                 playerObj:playSound("LauncherFire")
--                 Advanced_trajectory.ShootGrenade(playerObj, instanceItem("Base.PipeBomb"))
--                 SetLauncherStatus(playerObj, "Empty")
--             else
--                 local inv = playerObj:getInventory()
--                 local AmmoCanno = inv:FindAndReturn("GrenadeAmmo")
--                 if AmmoCanno then
--                     ISTimedActionQueue.add(ShootGrenadeReload:new(playerObj, 100, playerObj:getPrimaryHandItem(),
--                         "grenade"))
--                 end
--             end
--         end
--     end
-- end
-- local function Check()
--     Events.OnKeyPressed.Add(LaunchGrenadeLauncher)
-- end
-- local function OnGameStartCheckModinfo()
--     Events.OnGameStart.Add(Check)
--     Events.OnPlayerUpdate.Add(CheckGrenadelauncher)
-- end
-- Events.OnGameStart.Add(OnGameStartCheckModinfo)
