-- require "Advanced_trajectory_core"
-- HasEnterFireModeFlag = HasEnterFireModeFlag or false
-- local function HasShotGunlauncher(playerObj)
--     local MainGun = playerObj:getPrimaryHandItem()
--     if not MainGun then
--         return {false, false}
--     end
--     if MainGun:IsWeapon() and MainGun:isRanged() then
--         if MainGun:getStool() and MainGun:getStool():getType() == "M26_cat" then
--             return {true, true}
--         end
--         if MainGun:getStool() and MainGun:getStool():getType() == "M26_cat_empty" then
--             return {true, false}
--         end
--     end
--     return {false, false}
-- end
-- local function SetShotGunStatus(playerObj, type)
--     local MainGun = playerObj:getPrimaryHandItem()
--     if type == "Empty" then
--         local MagPart = instanceItem("Gunpart.M26_cat_empty")
--         MainGun:setWeaponPart("Stool", MagPart)
--     end
-- end
-- local function LaunchShotGunLauncher(_key)
--     if _key == getCore():getKey("LauchGrenadelauncherat") then
--         local playerObj = getPlayer()
--         local FlagNow = HasShotGunlauncher(playerObj)
--         if FlagNow[1] and playerObj:isAiming() then
--             if FlagNow[2] then
--                 playerObj:playSound("Striker12_catShoot")
--                 Advanced_trajectory.Shotgun(playerObj)
--                 SetShotGunStatus(playerObj, "Empty")
--             else
--                 local inv = playerObj:getInventory()
--                 local AmmoCanno = inv:FindAndReturn("Base.ShotgunShells")
--                 if AmmoCanno then
--                     ISTimedActionQueue.add(ShootGrenadeReload:new(playerObj, 15, playerObj:getPrimaryHandItem(),
--                         "ShotGun"))
--                 end
--             end
--         end
--     end
-- end
-- local function OnGameStartCheckModinfo()
--     Events.OnKeyPressed.Add(LaunchShotGunLauncher)
-- end
-- Events.OnGameStart.Add(OnGameStartCheckModinfo)
