/*
 * Decompiled with CFR 0.152.
 */
package org.javacord.api.entity.server;

public enum ServerFeature {
    ANIMATED_ICON,
    BANNER,
    COMMUNITY,
    DISCOVERABLE,
    FEATURABLE,
    INVITE_SPLASH,
    MEMBER_VERIFICATION_GATE_ENABLED,
    NEWS,
    PARTNERED,
    PREVIEW_ENABLED,
    VANITY_URL,
    VERIFIED,
    VIP_REGIONS,
    WELCOME_SCREEN_ENABLED,
    TICKETED_EVENTS_ENABLED,
    MONETIZATION_ENABLED,
    MORE_STICKERS,
    PRIVATE_THREADS,
    ANIMATED_BANNER,
    AUTO_MODERATION,
    INVITES_DISABLED;

}

