-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ct_oac_furniture_storage_01_24"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_0", "ct_oac_storage_01_2", "ct_oac_storage_01_8", "ct_oac_storage_01_10", "none"} }}
overlayMap["ct_oac_furniture_storage_01_28"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_4", "ct_oac_storage_01_6", "ct_oac_storage_01_12", "ct_oac_storage_01_14", "none"} }}
overlayMap["ct_oac_furniture_storage_01_32"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_16", "ct_oac_storage_01_18", "ct_oac_storage_01_24", "ct_oac_storage_01_26", "none"} }}
overlayMap["ct_oac_furniture_storage_01_25"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_9", "ct_oac_storage_01_3", "ct_oac_storage_01_1", "ct_oac_storage_01_11", "none"} }}
overlayMap["ct_oac_furniture_storage_01_29"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_13", "ct_oac_storage_01_7", "ct_oac_storage_01_5", "ct_oac_storage_01_15", "none"} }}
overlayMap["ct_oac_furniture_storage_01_33"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_25", "ct_oac_storage_01_19", "ct_oac_storage_01_17", "ct_oac_storage_01_27", "none"} }}
overlayMap["ct_oac_furniture_storage_01_26"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_160", "ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_30"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_160", "ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_34"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_160", "ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_27"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_31"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_35"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_36"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_20", "ct_oac_storage_01_22", "ct_oac_storage_01_28", "ct_oac_storage_01_30", "none"} }}
overlayMap["ct_oac_furniture_storage_01_40"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_32", "ct_oac_storage_01_34", "ct_oac_storage_01_40", "ct_oac_storage_01_42", "none"} }}
overlayMap["ct_oac_furniture_storage_01_44"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_36", "ct_oac_storage_01_38", "ct_oac_storage_01_44", "ct_oac_storage_01_46", "none"} }}
overlayMap["ct_oac_furniture_storage_01_37"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_31", "ct_oac_storage_01_21", "ct_oac_storage_01_23", "ct_oac_storage_01_29", "none"} }}
overlayMap["ct_oac_furniture_storage_01_41"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_43", "ct_oac_storage_01_33", "ct_oac_storage_01_35", "ct_oac_storage_01_41", "none"} }}
overlayMap["ct_oac_furniture_storage_01_45"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_47", "ct_oac_storage_01_37", "ct_oac_storage_01_39", "ct_oac_storage_01_45", "none"} }}
overlayMap["ct_oac_furniture_storage_01_38"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_42"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_46"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_39"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_43"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_47"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_80"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_56", "ct_oac_storage_01_58", "ct_oac_storage_01_64", "ct_oac_storage_01_66", "none"} }}
overlayMap["ct_oac_furniture_storage_01_84"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_60", "ct_oac_storage_01_62", "ct_oac_storage_01_68", "ct_oac_storage_01_70", "none"} }}
overlayMap["ct_oac_furniture_storage_01_81"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_57", "ct_oac_storage_01_65", "ct_oac_storage_01_59", "ct_oac_storage_01_67", "none"} }}
overlayMap["ct_oac_furniture_storage_01_85"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_61", "ct_oac_storage_01_69", "ct_oac_storage_01_63", "ct_oac_storage_01_71", "none"} }}
overlayMap["ct_oac_furniture_storage_01_82"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_86"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_83"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_87"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_104"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_88", "ct_oac_storage_01_96", "ct_oac_storage_01_90", "ct_oac_storage_01_98", "none"} }}
overlayMap["ct_oac_furniture_storage_01_108"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_104", "ct_oac_storage_01_112", "ct_oac_storage_01_106", "ct_oac_storage_01_114", "none"} }}
overlayMap["ct_oac_furniture_storage_01_112"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_120", "ct_oac_storage_01_128", "ct_oac_storage_01_122", "ct_oac_storage_01_130", "none"} }}
overlayMap["ct_oac_furniture_storage_01_105"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_89", "ct_oac_storage_01_97", "ct_oac_storage_01_91", "ct_oac_storage_01_99", "none"} }}
overlayMap["ct_oac_furniture_storage_01_109"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_105", "ct_oac_storage_01_113", "ct_oac_storage_01_107", "ct_oac_storage_01_115", "none"} }}
overlayMap["ct_oac_furniture_storage_01_113"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_121", "ct_oac_storage_01_129", "ct_oac_storage_01_123", "ct_oac_storage_01_131", "none"} }}
overlayMap["ct_oac_furniture_storage_01_106"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_92", "ct_oac_storage_01_94", "ct_oac_storage_01_100", "ct_oac_storage_01_102", "none"} }}
overlayMap["ct_oac_furniture_storage_01_110"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_108", "ct_oac_storage_01_110", "ct_oac_storage_01_116", "ct_oac_storage_01_118", "none"} }}
overlayMap["ct_oac_furniture_storage_01_114"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_124", "ct_oac_storage_01_126", "ct_oac_storage_01_132", "ct_oac_storage_01_134", "none"} }}
overlayMap["ct_oac_furniture_storage_01_107"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_93", "ct_oac_storage_01_95", "ct_oac_storage_01_103", "ct_oac_storage_01_101", "none"} }}
overlayMap["ct_oac_furniture_storage_01_111"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_109", "ct_oac_storage_01_111", "ct_oac_storage_01_119", "ct_oac_storage_01_117", "none"} }}
overlayMap["ct_oac_furniture_storage_01_115"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_125", "ct_oac_storage_01_127", "ct_oac_storage_01_135", "ct_oac_storage_01_133", "none"} }}
overlayMap["ct_oac_furniture_storage_01_116"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_120"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_124"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_162", "ct_oac_storage_01_164", "ct_oac_storage_01_160", "ct_oac_storage_01_166", "none"} }}
overlayMap["ct_oac_furniture_storage_01_117"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_121"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_125"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_161", "ct_oac_storage_01_163", "ct_oac_storage_01_165", "ct_oac_storage_01_167", "none"} }}
overlayMap["ct_oac_furniture_storage_01_118"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_92", "ct_oac_storage_01_94", "ct_oac_storage_01_100", "ct_oac_storage_01_102", "none"} }}
overlayMap["ct_oac_furniture_storage_01_122"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_108", "ct_oac_storage_01_110", "ct_oac_storage_01_116", "ct_oac_storage_01_118", "none"} }}
overlayMap["ct_oac_furniture_storage_01_126"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_124", "ct_oac_storage_01_126", "ct_oac_storage_01_132", "ct_oac_storage_01_134", "none"} }}
overlayMap["ct_oac_furniture_storage_01_119"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_93", "ct_oac_storage_01_95", "ct_oac_storage_01_103", "ct_oac_storage_01_101", "none"} }}
overlayMap["ct_oac_furniture_storage_01_123"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_109", "ct_oac_storage_01_111", "ct_oac_storage_01_119", "ct_oac_storage_01_117", "none"} }}
overlayMap["ct_oac_furniture_storage_01_127"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_125", "ct_oac_storage_01_127", "ct_oac_storage_01_135", "ct_oac_storage_01_133", "none"} }}
overlayMap["ct_oac_furniture_storage_01_132"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"ct_oac_storage_01_80"} }}
overlayMap["ct_oac_furniture_storage_01_133"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"ct_oac_storage_01_81"} }}
overlayMap["ct_oac_furniture_storage_01_134"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"ct_oac_storage_01_82"} }}
overlayMap["ct_oac_furniture_storage_01_135"] = {{ name = "other", chance = 2, usage = "tabletop", tiles = {"ct_oac_storage_01_83"} }}
overlayMap["ct_oac_furniture_storage_02_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"ct_oac_storage_01_48", "ct_oac_storage_01_52", "ct_oac_storage_01_54", "none"} }}
overlayMap["ct_oac_furniture_storage_02_1"] = {{ name = "other", chance = 1, usage = "", tiles = {"ct_oac_storage_01_49", "ct_oac_storage_01_53", "ct_oac_storage_01_55", "none"} }}
overlayMap["ct_oac_furniture_storage_02_2"] = {{ name = "other", chance = 2, usage = "", tiles = {"ct_oac_storage_01_50"} }}
overlayMap["ct_oac_furniture_storage_02_3"] = {{ name = "other", chance = 2, usage = "", tiles = {"ct_oac_storage_01_51"} }}
overlayMap["ct_oac_furniture_storage_02_4"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_74"} }}
overlayMap["ct_oac_furniture_storage_02_52"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_78"} }}
overlayMap["ct_oac_furniture_storage_02_5"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_75"} }}
overlayMap["ct_oac_furniture_storage_02_53"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_79"} }}
overlayMap["ct_oac_furniture_storage_02_12"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_72"} }}
overlayMap["ct_oac_furniture_storage_02_20"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_76"} }}
overlayMap["ct_oac_furniture_storage_02_13"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_73"} }}
overlayMap["ct_oac_furniture_storage_02_21"] = {{ name = "other", chance = 5, usage = "", tiles = {"ct_oac_storage_01_77"} }}
overlayMap["ct_oac_location_community_medical_01_36"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_136", "ct_oac_storage_01_140", "none"} }}
overlayMap["ct_oac_location_community_medical_01_40"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_144", "ct_oac_storage_01_148", "none"} }}
overlayMap["ct_oac_location_community_medical_01_44"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_152", "ct_oac_storage_01_156", "none"} }}
overlayMap["ct_oac_location_community_medical_01_37"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_137", "ct_oac_storage_01_141", "none"} }}
overlayMap["ct_oac_location_community_medical_01_41"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_145", "ct_oac_storage_01_149", "none"} }}
overlayMap["ct_oac_location_community_medical_01_45"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_153", "ct_oac_storage_01_157", "none"} }}
overlayMap["ct_oac_location_community_medical_01_38"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_138", "ct_oac_storage_01_142", "none"} }}
overlayMap["ct_oac_location_community_medical_01_42"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_146", "ct_oac_storage_01_150", "none"} }}
overlayMap["ct_oac_location_community_medical_01_46"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_154", "ct_oac_storage_01_158", "none"} }}
overlayMap["ct_oac_location_community_medical_01_39"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_139", "ct_oac_storage_01_143", "none"} }}
overlayMap["ct_oac_location_community_medical_01_43"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_147", "ct_oac_storage_01_151", "none"} }}
overlayMap["ct_oac_location_community_medical_01_47"] = {{ name = "other", chance = 1, usage = "tabletop", tiles = {"ct_oac_storage_01_155", "ct_oac_storage_01_159", "none"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
