LCCQF = LCCQF or {}

local Constants = {}

Constants.MODULE = "LaccckaQuestFramework"
Constants.VERSION = "0.3.4"
Constants.LOG_PREFIX = "[LCCQF]"

Constants.INTERACTION_RANGE = 3.25
Constants.SERVER_INTERACTION_RANGE = 4.0
Constants.RUNTIME_RESOLVE_PADDING = 1.0
Constants.RUNTIME_RECONCILE_INTERVAL_MS = 250
Constants.QUEST_UPDATE_INTERVAL_MS = 250
Constants.REQUEST_COOLDOWN_MS = 150
Constants.SESSION_TIMEOUT_MS = 15 * 60 * 1000
Constants.COMMAND_HISTORY_TIMEOUT_MS = 30 * 60 * 1000
Constants.MAX_IDENTIFIER_LENGTH = 96
Constants.MAX_DIALOGUE_CHOICES = 3

Constants.PERSISTENCE_TAG = "LCCQF_Persistence"
Constants.PERSISTENCE_SCHEMA_VERSION = 1
Constants.QUEST_PERSISTENCE_SCHEMA_VERSION = 1
Constants.KNOWLEDGE_PERSISTENCE_SCHEMA_VERSION = 1
Constants.RELATIONSHIP_PERSISTENCE_SCHEMA_VERSION = 1
Constants.FACTION_KNOWLEDGE_PERSISTENCE_SCHEMA_VERSION = 1
Constants.FACTION_RELATIONSHIP_PERSISTENCE_SCHEMA_VERSION = 1
Constants.FACTION_SITE_PERSISTENCE_SCHEMA_VERSION = 1
Constants.FACTION_SITE_MODDATA_KEY = "LCCQF_FactionSites"
Constants.FACTION_SITE_MAX_CANDIDATES = 128
Constants.FACTION_SITE_MAX_ROOMS_PER_PASS = 256
Constants.FACTION_SITE_DIAGNOSTIC_TOP_N = 5
Constants.FACTION_SITE_RESOURCE_SCAN_MAX_TILES = 4096
Constants.FACTION_SITE_RUNTIME_SCAN_MAX_TILES = 2048
Constants.FACTION_SITE_STOCK_SCAN_MAX_TILES = 4096
Constants.FACTION_SITE_STOCK_MAX_CONTAINERS = 128
Constants.FACTION_SITE_STOCK_MAX_ITEMS = 4096
Constants.FACTION_SITE_STOCK_REFRESH_WORLD_HOURS = 1 / 6
Constants.FACTION_SITE_ECONOMY_LEDGER_MAX_ENTRIES = 256
Constants.FACTION_SITE_ECONOMY_LEDGER_MAX_RECENT_SOURCES = 1024
Constants.FACTION_SITE_CONSUMPTION_MAX_ITEMS_PER_PASS = 16
Constants.FACTION_SITE_TRANSFER_INTENT_TTL_MS = 15000
Constants.FACTION_SITE_TRANSFER_POLL_INTERVAL_MS = 100
Constants.FACTION_SITE_TRANSFER_REFRESH_DEBOUNCE_MS = 500
Constants.FACTION_SITE_TRANSFER_MAX_DISTANCE = 6
Constants.FACTION_SITE_TRANSFER_MAX_PENDING_PER_PLAYER = 64
Constants.FACTION_SITE_TRANSFER_OWNERSHIP_SCAN_MAX_ITEMS = 4096
Constants.CHARACTER_ID_MODDATA_KEY = "lccqCharacterId"

Constants.COMMAND = {
    REQUEST_DIALOGUE = "RequestDialogue",
    CHOOSE_DIALOGUE = "ChooseDialogue",
    CLOSE_DIALOGUE = "CloseDialogue",
    SPAWN_TEST_NPC = "SpawnTestNPC",
    REQUEST_RUNTIME_BINDINGS = "RequestRuntimeBindings",
    RUNTIME_BINDINGS = "RuntimeBindings",
    RUNTIME_BINDING_UPSERT = "RuntimeBindingUpsert",
    RUNTIME_BINDING_REMOVE = "RuntimeBindingRemove",
    REQUEST_QUESTS = "RequestQuests",
    QUESTS = "Quests",
    QUEST_UPSERT = "QuestUpsert",
    QUEST_EVENT = "QuestEvent",
    REQUEST_KNOWLEDGE = "RequestKnowledge",
    KNOWLEDGE = "Knowledge",
    KNOWN_PERSON_UPSERT = "KnownPersonUpsert",
    REQUEST_FACTIONS = "RequestFactions",
    FACTIONS = "Factions",
    KNOWN_FACTION_UPSERT = "KnownFactionUpsert",
    REQUEST_FACTION_SITES_DEBUG = "RequestFactionSitesDebug",
    FACTION_SITES_DEBUG = "FactionSitesDebug",
    REPORT_SETTLEMENT_TRANSFER_INTENT = "ReportSettlementTransferIntent",
    DIALOGUE_STATE = "DialogueState",
    DIALOGUE_CLOSED = "DialogueClosed",
    STATUS = "Status",
}

Constants.TEST_NPC_ID = "lccq_test_npc_01"
Constants.TEST_NPC_BID = "e6b19154-2cf4-4ef9-9ad5-1ac8c85a0001"
Constants.TEST_NPC_CID = "c2c9d2b8-7a21-4e66-a8d9-1cfa01caa001"
Constants.TEST_FACTION_ID = "lccq_checkpoint_survivors"
Constants.TEST_QUEST_ID = "lccq_test_checkpoint"
Constants.TEST_QUEST_2_ID = "lccq_test_supply_run"
Constants.TEST_QUEST_BRANCH_SUPPORT_ID = "lccq_test_branch_support"
Constants.TEST_QUEST_BRANCH_INDEPENDENT_ID = "lccq_test_branch_independent"
Constants.TEST_BRANCH_GROUP_ID = "checkpoint_alignment"
Constants.TEST_BRANCH_SUPPORT_OPTION = "support_group"
Constants.TEST_BRANCH_INDEPENDENT_OPTION = "stay_independent"

LCCQF.Constants = Constants
return Constants
