/*
 * Decompiled with CFR 0.152.
 */
package oshi.ffm.mac;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.foreign.ValueLayout;

public interface MacSystem {
    public static final int HOST_LOAD_INFO = 1;
    public static final int HOST_VM_INFO = 2;
    public static final int HOST_CPU_LOAD_INFO = 3;
    public static final int HOST_VM_INFO64 = 4;
    public static final int CPU_STATE_MAX = 4;
    public static final int CPU_STATE_USER = 0;
    public static final int CPU_STATE_SYSTEM = 1;
    public static final int CPU_STATE_IDLE = 2;
    public static final int CPU_STATE_NICE = 3;
    public static final int PROCESSOR_BASIC_INFO = 1;
    public static final int PROCESSOR_CPU_LOAD_INFO = 2;
    public static final int UINT64_SIZE = (int)ValueLayout.JAVA_LONG.byteSize();
    public static final int INT_SIZE = (int)ValueLayout.JAVA_INT.byteSize();
    public static final int MAXCOMLEN = 16;
    public static final int MAXPATHLEN = 1024;
    public static final int PROC_PIDPATHINFO_MAXSIZE = 4096;
    public static final int PROC_ALL_PIDS = 1;
    public static final int PROC_PIDTASKALLINFO = 2;
    public static final int PROC_PIDTBSDINFO = 3;
    public static final int PROC_PIDTASKINFO = 4;
    public static final int PROC_PIDVNODEPATHINFO = 9;
    public static final int MFSTYPENAMELEN = 16;
    public static final int MNAMELEN = 1024;
    public static final int MNT_WAIT = 1;
    public static final int MNT_NOWAIT = 16;
    public static final int MNT_DWAIT = 256;
    public static final int RUSAGE_INFO_V2 = 2;
    public static final int PROC_PIDLISTFDS = 1;
    public static final int PROX_FDTYPE_SOCKET = 2;
    public static final int PROC_PIDFDSOCKETINFO = 3;
    public static final int TSI_T_NTIMERS = 4;
    public static final int SOCKINFO_IN = 1;
    public static final int SOCKINFO_TCP = 2;
    public static final int UTX_USERSIZE = 256;
    public static final int UTX_LINESIZE = 32;
    public static final int UTX_IDSIZE = 4;
    public static final int UTX_HOSTSIZE = 256;
    public static final int AF_INET = 2;
    public static final int AF_INET6 = 30;
    public static final StructLayout PROC_BSD_INFO = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("pbi_flags"), ValueLayout.JAVA_INT.withName("pbi_status"), ValueLayout.JAVA_INT.withName("pbi_xstatus"), ValueLayout.JAVA_INT.withName("pbi_pid"), ValueLayout.JAVA_INT.withName("pbi_ppid"), ValueLayout.JAVA_INT.withName("pbi_uid"), ValueLayout.JAVA_INT.withName("pbi_gid"), ValueLayout.JAVA_INT.withName("pbi_ruid"), ValueLayout.JAVA_INT.withName("pbi_rgid"), ValueLayout.JAVA_INT.withName("pbi_svuid"), ValueLayout.JAVA_INT.withName("pbi_svgid"), ValueLayout.JAVA_INT.withName("rfu_1"), MemoryLayout.sequenceLayout(16L, ValueLayout.JAVA_BYTE).withName("pbi_comm"), MemoryLayout.sequenceLayout(32L, ValueLayout.JAVA_BYTE).withName("pbi_name"), ValueLayout.JAVA_INT.withName("pbi_nfiles"), ValueLayout.JAVA_INT.withName("pbi_pgid"), ValueLayout.JAVA_INT.withName("pbi_pjobc"), ValueLayout.JAVA_INT.withName("e_tdev"), ValueLayout.JAVA_INT.withName("e_tpgid"), ValueLayout.JAVA_INT.withName("pbi_nice"), ValueLayout.JAVA_LONG.withName("pbi_start_tvsec"), ValueLayout.JAVA_LONG.withName("pbi_start_tvusec"));
    public static final MemoryLayout.PathElement PBI_STATUS = MemoryLayout.PathElement.groupElement("pbi_status");
    public static final MemoryLayout.PathElement PBI_FLAGS = MemoryLayout.PathElement.groupElement("pbi_flags");
    public static final MemoryLayout.PathElement PBI_PPID = MemoryLayout.PathElement.groupElement("pbi_ppid");
    public static final MemoryLayout.PathElement PBI_UID = MemoryLayout.PathElement.groupElement("pbi_uid");
    public static final MemoryLayout.PathElement PBI_GID = MemoryLayout.PathElement.groupElement("pbi_gid");
    public static final MemoryLayout.PathElement PBI_COMM = MemoryLayout.PathElement.groupElement("pbi_comm");
    public static final MemoryLayout.PathElement PBI_NFILES = MemoryLayout.PathElement.groupElement("pbi_nfiles");
    public static final MemoryLayout.PathElement PBI_START_TVSEC = MemoryLayout.PathElement.groupElement("pbi_start_tvsec");
    public static final MemoryLayout.PathElement PBI_START_TVUSEC = MemoryLayout.PathElement.groupElement("pbi_start_tvusec");
    public static final StructLayout PROC_TASK_INFO = MemoryLayout.structLayout(ValueLayout.JAVA_LONG.withName("pti_virtual_size"), ValueLayout.JAVA_LONG.withName("pti_resident_size"), ValueLayout.JAVA_LONG.withName("pti_total_user"), ValueLayout.JAVA_LONG.withName("pti_total_system"), ValueLayout.JAVA_LONG.withName("pti_threads_user"), ValueLayout.JAVA_LONG.withName("pti_threads_system"), ValueLayout.JAVA_INT.withName("pti_policy"), ValueLayout.JAVA_INT.withName("pti_faults"), ValueLayout.JAVA_INT.withName("pti_pageins"), ValueLayout.JAVA_INT.withName("pti_cow_faults"), ValueLayout.JAVA_INT.withName("pti_messages_sent"), ValueLayout.JAVA_INT.withName("pti_messages_received"), ValueLayout.JAVA_INT.withName("pti_syscalls_mach"), ValueLayout.JAVA_INT.withName("pti_syscalls_unix"), ValueLayout.JAVA_INT.withName("pti_csw"), ValueLayout.JAVA_INT.withName("pti_threadnum"), ValueLayout.JAVA_INT.withName("pti_numrunning"), ValueLayout.JAVA_INT.withName("pti_priority"));
    public static final MemoryLayout.PathElement PTI_VIRTUAL_SIZE = MemoryLayout.PathElement.groupElement("pti_virtual_size");
    public static final MemoryLayout.PathElement PTI_RESIDENT_SIZE = MemoryLayout.PathElement.groupElement("pti_resident_size");
    public static final MemoryLayout.PathElement PTI_TOTAL_USER = MemoryLayout.PathElement.groupElement("pti_total_user");
    public static final MemoryLayout.PathElement PTI_TOTAL_SYSTEM = MemoryLayout.PathElement.groupElement("pti_total_system");
    public static final MemoryLayout.PathElement PTI_FAULTS = MemoryLayout.PathElement.groupElement("pti_faults");
    public static final MemoryLayout.PathElement PTI_PAGEINS = MemoryLayout.PathElement.groupElement("pti_pageins");
    public static final MemoryLayout.PathElement PTI_CSW = MemoryLayout.PathElement.groupElement("pti_csw");
    public static final MemoryLayout.PathElement PTI_THREADNUM = MemoryLayout.PathElement.groupElement("pti_threadnum");
    public static final MemoryLayout.PathElement PTI_PRIORITY = MemoryLayout.PathElement.groupElement("pti_priority");
    public static final StructLayout PROC_TASK_ALL_INFO = MemoryLayout.structLayout(PROC_BSD_INFO.withName("pbsd"), PROC_TASK_INFO.withName("ptinfo"));
    public static final MemoryLayout.PathElement PBSD = MemoryLayout.PathElement.groupElement("pbsd");
    public static final MemoryLayout.PathElement PTINFO = MemoryLayout.PathElement.groupElement("ptinfo");
    public static final StructLayout PASSWD = MemoryLayout.structLayout(ValueLayout.ADDRESS.withName("pw_name"), ValueLayout.ADDRESS.withName("pw_passwd"), ValueLayout.JAVA_INT.withName("pw_uid"), ValueLayout.JAVA_INT.withName("pw_gid"), ValueLayout.JAVA_LONG.withName("pw_change"), ValueLayout.ADDRESS.withName("pw_class"), ValueLayout.ADDRESS.withName("pw_gecos"), ValueLayout.ADDRESS.withName("pw_dir"), ValueLayout.ADDRESS.withName("pw_shell"), ValueLayout.JAVA_LONG.withName("pw_expire"), ValueLayout.ADDRESS.withName("pw_fields"));
    public static final StructLayout GROUP = MemoryLayout.structLayout(ValueLayout.ADDRESS.withName("gr_name"), ValueLayout.ADDRESS.withName("gr_passwd"), ValueLayout.ADDRESS.withName("gr_gid"), ValueLayout.ADDRESS.withName("gr_mem"));
    public static final StructLayout RUSAGEINFOV2 = MemoryLayout.structLayout(MemoryLayout.sequenceLayout(16L, ValueLayout.JAVA_BYTE).withName("ri_uuid"), ValueLayout.JAVA_LONG.withName("ri_user_time"), ValueLayout.JAVA_LONG.withName("ri_system_time"), ValueLayout.JAVA_LONG.withName("ri_pkg_idle_wkups"), ValueLayout.JAVA_LONG.withName("ri_interrupt_wkups"), ValueLayout.JAVA_LONG.withName("ri_pageins"), ValueLayout.JAVA_LONG.withName("ri_wired_size"), ValueLayout.JAVA_LONG.withName("ri_resident_size"), ValueLayout.JAVA_LONG.withName("ri_phys_footprint"), ValueLayout.JAVA_LONG.withName("ri_proc_start_abstime"), ValueLayout.JAVA_LONG.withName("ri_proc_exit_abstime"), ValueLayout.JAVA_LONG.withName("ri_child_user_time"), ValueLayout.JAVA_LONG.withName("ri_child_system_time"), ValueLayout.JAVA_LONG.withName("ri_child_pkg_idle_wkups"), ValueLayout.JAVA_LONG.withName("ri_child_interrupt_wkups"), ValueLayout.JAVA_LONG.withName("ri_child_pageins"), ValueLayout.JAVA_LONG.withName("ri_child_elapsed_abstime"), ValueLayout.JAVA_LONG.withName("ri_diskio_bytesread"), ValueLayout.JAVA_LONG.withName("ri_diskio_byteswritten"));
    public static final MemoryLayout.PathElement RI_DISKIO_BYTESREAD = MemoryLayout.PathElement.groupElement("ri_diskio_bytesread");
    public static final MemoryLayout.PathElement RI_DISKIO_BYTESWRITTEN = MemoryLayout.PathElement.groupElement("ri_diskio_byteswritten");
    public static final StructLayout VNODE_INFO_PATH = MemoryLayout.structLayout(MemoryLayout.paddingLayout(1216L), MemoryLayout.sequenceLayout(1024L, ValueLayout.JAVA_BYTE).withName("vip_path"));
    public static final MemoryLayout.PathElement VIP_PATH = MemoryLayout.PathElement.groupElement("vip_path");
    public static final StructLayout VNODE_PATH_INFO = MemoryLayout.structLayout(VNODE_INFO_PATH.withName("pvi_cdir"), VNODE_INFO_PATH.withName("pvi_rdir"));
    public static final MemoryLayout.PathElement PVI_CDIR = MemoryLayout.PathElement.groupElement("pvi_cdir");
    public static final StructLayout TIMEVAL = MemoryLayout.structLayout(ValueLayout.JAVA_LONG.withName("tv_sec"), ValueLayout.JAVA_INT.withName("tv_usec"));
    public static final StructLayout RLIMIT = MemoryLayout.structLayout(ValueLayout.JAVA_LONG.withName("rlim_cur"), ValueLayout.JAVA_LONG.withName("rlim_max"));
    public static final MemoryLayout.PathElement RLIM_CUR = MemoryLayout.PathElement.groupElement("rlim_cur");
    public static final MemoryLayout.PathElement RLIM_MAX = MemoryLayout.PathElement.groupElement("rlim_max");
    public static final StructLayout STATFS = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("f_bsize"), ValueLayout.JAVA_INT.withName("f_iosize"), ValueLayout.JAVA_LONG.withName("f_blocks"), ValueLayout.JAVA_LONG.withName("f_bfree"), ValueLayout.JAVA_LONG.withName("f_bavail"), ValueLayout.JAVA_LONG.withName("f_files"), ValueLayout.JAVA_LONG.withName("f_ffree"), MemoryLayout.sequenceLayout(2L, ValueLayout.JAVA_INT).withName("f_fsid"), ValueLayout.JAVA_INT.withName("f_owner"), ValueLayout.JAVA_INT.withName("f_type"), ValueLayout.JAVA_INT.withName("f_flags"), ValueLayout.JAVA_INT.withName("f_fssubtype"), MemoryLayout.sequenceLayout(16L, ValueLayout.JAVA_BYTE).withName("f_fstypename"), MemoryLayout.sequenceLayout(1024L, ValueLayout.JAVA_BYTE).withName("f_mntonname"), MemoryLayout.sequenceLayout(1024L, ValueLayout.JAVA_BYTE).withName("f_mntfromname"), MemoryLayout.paddingLayout(32L).withName("f_reserved"));
    public static final MemoryLayout.PathElement F_FILES = MemoryLayout.PathElement.groupElement("f_files");
    public static final MemoryLayout.PathElement F_FFREE = MemoryLayout.PathElement.groupElement("f_ffree");
    public static final MemoryLayout.PathElement F_FSTYPENAME = MemoryLayout.PathElement.groupElement("f_fstypename");
    public static final MemoryLayout.PathElement F_FLAGS = MemoryLayout.PathElement.groupElement("f_flags");
    public static final MemoryLayout.PathElement F_MNTONNAME = MemoryLayout.PathElement.groupElement("f_mntonname");
    public static final MemoryLayout.PathElement F_MNTFROMNAME = MemoryLayout.PathElement.groupElement("f_mntfromname");
    public static final StructLayout PROC_FD_INFO = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("proc_fd"), ValueLayout.JAVA_INT.withName("proc_fdtype"));
    public static final MemoryLayout.PathElement PROC_FD = MemoryLayout.PathElement.groupElement("proc_fd");
    public static final MemoryLayout.PathElement PROC_FDTYPE = MemoryLayout.PathElement.groupElement("proc_fdtype");
    public static final StructLayout IN_SOCK_INFO = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("insi_fport"), ValueLayout.JAVA_INT.withName("insi_lport"), ValueLayout.JAVA_LONG.withName("insi_gencnt"), ValueLayout.JAVA_INT.withName("insi_flags"), ValueLayout.JAVA_INT.withName("insi_flow"), ValueLayout.JAVA_BYTE.withName("insi_vflag"), ValueLayout.JAVA_BYTE.withName("insi_ip_ttl"), MemoryLayout.paddingLayout(2L), ValueLayout.JAVA_INT.withName("rfu_1"), MemoryLayout.sequenceLayout(4L, ValueLayout.JAVA_INT).withName("insi_faddr"), MemoryLayout.sequenceLayout(4L, ValueLayout.JAVA_INT).withName("insi_laddr"), ValueLayout.JAVA_BYTE.withName("insi_v4"), MemoryLayout.sequenceLayout(9L, ValueLayout.JAVA_BYTE).withName("insi_v6"));
    public static final MemoryLayout.PathElement INSI_FPORT = MemoryLayout.PathElement.groupElement("insi_fport");
    public static final MemoryLayout.PathElement INSI_LPORT = MemoryLayout.PathElement.groupElement("insi_lport");
    public static final MemoryLayout.PathElement INSI_VFLAG = MemoryLayout.PathElement.groupElement("insi_vflag");
    public static final MemoryLayout.PathElement INSI_FADDR = MemoryLayout.PathElement.groupElement("insi_faddr");
    public static final MemoryLayout.PathElement INSI_LADDR = MemoryLayout.PathElement.groupElement("insi_laddr");
    public static final StructLayout TCP_SOCK_INFO = MemoryLayout.structLayout(IN_SOCK_INFO.withName("tcpsi_ini"), MemoryLayout.paddingLayout(2L), ValueLayout.JAVA_INT.withName("tcpsi_state"), MemoryLayout.sequenceLayout(4L, ValueLayout.JAVA_INT).withName("tcpsi_timer"), ValueLayout.JAVA_INT.withName("tcpsi_mss"), ValueLayout.JAVA_INT.withName("tcpsi_flags"), ValueLayout.JAVA_INT.withName("rfu_1"), MemoryLayout.paddingLayout(4L), ValueLayout.JAVA_LONG.withName("tcpsi_tp"));
    public static final MemoryLayout.PathElement TCPSI_INI = MemoryLayout.PathElement.groupElement("tcpsi_ini");
    public static final MemoryLayout.PathElement TCPSI_STATE = MemoryLayout.PathElement.groupElement("tcpsi_state");
    public static final StructLayout PROC_FILE_INFO = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("fi_openflags"), ValueLayout.JAVA_INT.withName("fi_status"), ValueLayout.JAVA_LONG.withName("fi_offset"), ValueLayout.JAVA_INT.withName("fi_type"), ValueLayout.JAVA_INT.withName("fi_guardflags"));
    public static final StructLayout SOCKET_INFO = MemoryLayout.structLayout(MemoryLayout.sequenceLayout(17L, ValueLayout.JAVA_LONG).withName("soi_stat"), ValueLayout.JAVA_LONG.withName("soi_so"), ValueLayout.JAVA_LONG.withName("soi_pcb"), ValueLayout.JAVA_INT.withName("soi_type"), ValueLayout.JAVA_INT.withName("soi_protocol"), ValueLayout.JAVA_INT.withName("soi_family"), ValueLayout.JAVA_SHORT.withName("soi_options"), ValueLayout.JAVA_SHORT.withName("soi_linger"), ValueLayout.JAVA_SHORT.withName("soi_state"), ValueLayout.JAVA_SHORT.withName("soi_qlen"), ValueLayout.JAVA_SHORT.withName("soi_incqlen"), ValueLayout.JAVA_SHORT.withName("soi_qlimit"), ValueLayout.JAVA_SHORT.withName("soi_timeo"), ValueLayout.JAVA_SHORT.withName("soi_error"), ValueLayout.JAVA_INT.withName("soi_oobmark"), MemoryLayout.sequenceLayout(6L, ValueLayout.JAVA_INT).withName("soi_rcv"), MemoryLayout.sequenceLayout(6L, ValueLayout.JAVA_INT).withName("soi_snd"), ValueLayout.JAVA_INT.withName("soi_kind"), ValueLayout.JAVA_INT.withName("rfu_1"), MemoryLayout.paddingLayout(524L).withName("soi_proto"));
    public static final MemoryLayout.PathElement SOI_FAMILY = MemoryLayout.PathElement.groupElement("soi_family");
    public static final MemoryLayout.PathElement SOI_KIND = MemoryLayout.PathElement.groupElement("soi_kind");
    public static final MemoryLayout.PathElement SOI_QLEN = MemoryLayout.PathElement.groupElement("soi_qlen");
    public static final MemoryLayout.PathElement SOI_INCQLEN = MemoryLayout.PathElement.groupElement("soi_incqlen");
    public static final MemoryLayout.PathElement SOI_PROTO = MemoryLayout.PathElement.groupElement("soi_proto");
    public static final StructLayout SOCKET_FD_INFO = MemoryLayout.structLayout(PROC_FILE_INFO.withName("pfi"), SOCKET_INFO.withName("psi"));
    public static final MemoryLayout.PathElement PFI = MemoryLayout.PathElement.groupElement("pfi");
    public static final MemoryLayout.PathElement PSI = MemoryLayout.PathElement.groupElement("psi");
    public static final StructLayout VM_STATISTICS = MemoryLayout.structLayout(ValueLayout.JAVA_INT.withName("free_count"), ValueLayout.JAVA_INT.withName("active_count"), ValueLayout.JAVA_INT.withName("inactive_count"), ValueLayout.JAVA_INT.withName("wire_count"), ValueLayout.JAVA_INT.withName("zero_fill_count"), ValueLayout.JAVA_INT.withName("reactivations"), ValueLayout.JAVA_INT.withName("pageins"), ValueLayout.JAVA_INT.withName("pageouts"), ValueLayout.JAVA_INT.withName("faults"), ValueLayout.JAVA_INT.withName("cow_faults"), ValueLayout.JAVA_INT.withName("lookups"), ValueLayout.JAVA_INT.withName("hits"));
    public static final MemoryLayout.PathElement VM_FREE_COUNT = MemoryLayout.PathElement.groupElement("free_count");
    public static final MemoryLayout.PathElement VM_INACTIVE_COUNT = MemoryLayout.PathElement.groupElement("inactive_count");
    public static final MemoryLayout.PathElement VM_PAGEINS = MemoryLayout.PathElement.groupElement("pageins");
    public static final MemoryLayout.PathElement VM_PAGEOUTS = MemoryLayout.PathElement.groupElement("pageouts");
    public static final StructLayout XSW_USAGE = MemoryLayout.structLayout(ValueLayout.JAVA_LONG.withName("xsu_total"), ValueLayout.JAVA_LONG.withName("xsu_avail"), ValueLayout.JAVA_LONG.withName("xsu_used"), ValueLayout.JAVA_INT.withName("xsu_pagesize"), ValueLayout.JAVA_INT.withName("xsu_encrypted"));
    public static final MemoryLayout.PathElement XSW_USAGE_USED = MemoryLayout.PathElement.groupElement("xsu_used");
    public static final MemoryLayout.PathElement XSW_USAGE_TOTAL = MemoryLayout.PathElement.groupElement("xsu_total");
}

