-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ct_oac_fixtures_counters_01_1"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_1", "ct_oac_fixtures_overlay_counters_01_0"} }}
overlayMap["ct_oac_fixtures_counters_01_3"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_2", "ct_oac_fixtures_overlay_counters_01_3"} }}
overlayMap["ct_oac_fixtures_counters_01_5"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_4", "ct_oac_fixtures_overlay_counters_01_5"} }}
overlayMap["ct_oac_fixtures_counters_01_7"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_6", "ct_oac_fixtures_overlay_counters_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_9"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_8", "ct_oac_fixtures_overlay_counters_01_9"} }}
overlayMap["ct_oac_fixtures_counters_01_11"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_10", "ct_oac_fixtures_overlay_counters_01_11"} }}
overlayMap["ct_oac_fixtures_counters_01_13"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_12", "ct_oac_fixtures_overlay_counters_01_13"} }}
overlayMap["ct_oac_fixtures_counters_01_15"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_14", "ct_oac_fixtures_overlay_counters_01_15"} }}
overlayMap["ct_oac_fixtures_counters_01_33"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_16", "ct_oac_fixtures_overlay_counters_01_17"} }}
overlayMap["ct_oac_fixtures_counters_01_35"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_18", "ct_oac_fixtures_overlay_counters_01_19"} }}
overlayMap["ct_oac_fixtures_counters_01_37"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_20", "ct_oac_fixtures_overlay_counters_01_21"} }}
overlayMap["ct_oac_fixtures_counters_01_39"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_22", "ct_oac_fixtures_overlay_counters_01_23"} }}
overlayMap["ct_oac_fixtures_counters_01_41"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_24", "ct_oac_fixtures_overlay_counters_01_25"} }}
overlayMap["ct_oac_fixtures_counters_01_43"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_26", "ct_oac_fixtures_overlay_counters_01_27"} }}
overlayMap["ct_oac_fixtures_counters_01_45"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_28", "ct_oac_fixtures_overlay_counters_01_29"} }}
overlayMap["ct_oac_fixtures_counters_01_47"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_30", "ct_oac_fixtures_overlay_counters_01_31"} }}
overlayMap["ct_oac_fixtures_counters_01_49"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_32", "ct_oac_fixtures_overlay_counters_01_33"} }}
overlayMap["ct_oac_fixtures_counters_01_51"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_34", "ct_oac_fixtures_overlay_counters_01_35"} }}
overlayMap["ct_oac_fixtures_counters_01_53"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_36", "ct_oac_fixtures_overlay_counters_01_37"} }}
overlayMap["ct_oac_fixtures_counters_01_55"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_38", "ct_oac_fixtures_overlay_counters_01_39"} }}
overlayMap["ct_oac_fixtures_counters_01_57"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_40", "ct_oac_fixtures_overlay_counters_01_41"} }}
overlayMap["ct_oac_fixtures_counters_01_59"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_42", "ct_oac_fixtures_overlay_counters_01_43"} }}
overlayMap["ct_oac_fixtures_counters_01_61"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_44", "ct_oac_fixtures_overlay_counters_01_45"} }}
overlayMap["ct_oac_fixtures_counters_01_63"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_46", "ct_oac_fixtures_overlay_counters_01_47"} }}
overlayMap["ct_oac_fixtures_counters_01_65"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_48", "ct_oac_fixtures_overlay_counters_01_49"} }}
overlayMap["ct_oac_fixtures_counters_01_67"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_50", "ct_oac_fixtures_overlay_counters_01_51"} }}
overlayMap["ct_oac_fixtures_counters_01_69"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_52", "ct_oac_fixtures_overlay_counters_01_53"} }}
overlayMap["ct_oac_fixtures_counters_01_71"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_54", "ct_oac_fixtures_overlay_counters_01_55"} }}
overlayMap["ct_oac_fixtures_counters_01_73"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_56", "ct_oac_fixtures_overlay_counters_01_57"} }}
overlayMap["ct_oac_fixtures_counters_01_75"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_58", "ct_oac_fixtures_overlay_counters_01_59"} }}
overlayMap["ct_oac_fixtures_counters_01_77"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_60", "ct_oac_fixtures_overlay_counters_01_61"} }}
overlayMap["ct_oac_fixtures_counters_01_79"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_fixtures_overlay_counters_01_62", "ct_oac_fixtures_overlay_counters_01_63"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
