function ChangeWeaponSkin(playeObj, MainGun, Skin)
    -- local ChaneWeapon = MainGun:getType()
    -- local result = instanceItem(ChaneWeapon);
    -- if (MainGun:isContainsClip() == true) then
    --     ISTimedActionQueue.add(ISEjectMagazine:new(playeObj, MainGun))
    -- else
    --     result:setCondition(MainGun:getCondition());
    --     result:setFireMode(MainGun:getFireMode());
    --     if MainGun:isRoundChambered() == true then
    --         result:setRoundChambered(true);
    --     end
    --     if (result:isAimedFirearm() and MainGun:isAimedFirearm()) then
    --         result:attachWeaponPart(MainGun:getWeaponPart("Scope"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Canon"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Stock"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Sling"))
    --         if MainGun:isContainsClip() == true then
    --             result:attachWeaponPart(MainGun:getWeaponPart("Clip"))
    --         end
    --         result:attachWeaponPart(MainGun:getWeaponPart("RecoilPad"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Light"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Laser"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Stool"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("Grip"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("R_Scope"))
    --         result:attachWeaponPart(MainGun:getWeaponPart("L_Scope"))
    --         result:attachWeaponPart(Skin)
    --         result:attachWeaponPart(MainGun:getWeaponPart("Misc"))
    --     end
    --     local OldModData = MainGun:getModData()
    --     local NewModData = result:getModData()
    --     if OldModData then
    --         for k, v in pairs(OldModData) do
    --             if AWCWF_AllowModDataTable[k] then
    --                 NewModData[k] = v
    --             end
    --         end
    --     end
    --     playeObj:getInventory():AddItem(result);
    --     if MainGun:getAttachedSlot() ~= nil then
    --         -- playeObj:setAttachedItem(MainGun:getAttachedToModel(), result);
    --         result:setAttachedSlot(MainGun:getAttachedSlot())
    --         result:setAttachedSlotType(MainGun:getAttachedSlotType())
    --         result:setAttachedToModel(MainGun:getAttachedToModel());
    --     end

    --     local inv = playeObj:getInventory()
    --     inv:DoRemoveItem(MainGun);
    --     if (instanceof(result, "HandWeapon")) then
    --         playeObj:setPrimaryHandItem(result)
    --         if (result:isRequiresEquippedBothHands() or result:isTwoHandWeapon()) then
    --             -- playeObj:setSecondaryHandItem(nil)
    --             playeObj:setSecondaryHandItem(result)
    --             return result
    --             -- print(result)
    --         else
    --             playeObj:setSecondaryHandItem(nil)
    --         end
    --     end
    -- end
end
