-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ct_oac_location_business_office_generic_01_16"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_0", "ct_oac_office_01_1"} }}
overlayMap["ct_oac_location_business_office_generic_01_18"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_16", "ct_oac_office_01_17"} }}
overlayMap["ct_oac_location_business_office_generic_01_20"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_32", "ct_oac_office_01_33"} }}
overlayMap["ct_oac_location_business_office_generic_01_17"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_2", "ct_oac_office_01_3"} }}
overlayMap["ct_oac_location_business_office_generic_01_19"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_18", "ct_oac_office_01_19"} }}
overlayMap["ct_oac_location_business_office_generic_01_21"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_34", "ct_oac_office_01_35"} }}
overlayMap["ct_oac_location_business_office_generic_01_24"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_8", "ct_oac_office_01_9"} }}
overlayMap["ct_oac_location_business_office_generic_01_26"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_24", "ct_oac_office_01_25"} }}
overlayMap["ct_oac_location_business_office_generic_01_28"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_40", "ct_oac_office_01_41"} }}
overlayMap["ct_oac_location_business_office_generic_01_25"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_10", "ct_oac_office_01_11"} }}
overlayMap["ct_oac_location_business_office_generic_01_27"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_26", "ct_oac_office_01_27"} }}
overlayMap["ct_oac_location_business_office_generic_01_29"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_42", "ct_oac_office_01_43"} }}
overlayMap["ct_oac_location_business_office_generic_01_32"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_4", "ct_oac_office_01_5"} }}
overlayMap["ct_oac_location_business_office_generic_01_36"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_20", "ct_oac_office_01_21"} }}
overlayMap["ct_oac_location_business_office_generic_01_48"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_36", "ct_oac_office_01_37"} }}
overlayMap["ct_oac_location_business_office_generic_01_33"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_6", "ct_oac_office_01_7"} }}
overlayMap["ct_oac_location_business_office_generic_01_37"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_22", "ct_oac_office_01_23"} }}
overlayMap["ct_oac_location_business_office_generic_01_49"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_38", "ct_oac_office_01_39"} }}
overlayMap["ct_oac_location_business_office_generic_01_34"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_12", "ct_oac_office_01_13"} }}
overlayMap["ct_oac_location_business_office_generic_01_38"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_28", "ct_oac_office_01_29"} }}
overlayMap["ct_oac_location_business_office_generic_01_50"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_44", "ct_oac_office_01_45"} }}
overlayMap["ct_oac_location_business_office_generic_01_35"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_14", "ct_oac_office_01_15"} }}
overlayMap["ct_oac_location_business_office_generic_01_39"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_30", "ct_oac_office_01_31"} }}
overlayMap["ct_oac_location_business_office_generic_01_51"] = {{ name = "other", chance = 4, usage = "", tiles = {"ct_oac_office_01_46", "ct_oac_office_01_47"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
