require('PaintVehicleConfig')

if getActivatedMods():contains("PaintYourRide") and PaintVehicleConfig then
    PaintVehicleConfig.addVehicle("Base.pzkMinivanStellaris", 27)


    PaintVehicleConfig.addVehicle("Base.pzkVanBrig", 35)
    PaintVehicleConfig.addVehicle("Base.pzkVanCamper", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierMaroca", 22)
    PaintVehicleConfig.addVehicle("Base.pzkPickUpTruck93", 31)
    PaintVehicleConfig.addVehicle("Base.pzkDashDeluxo", 27)
    PaintVehicleConfig.addVehicle("Base.pzkCarMuscle", 27)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinGalloper", 33)
    PaintVehicleConfig.addVehicle("Base.pzkHMMV", 40)
    PaintVehicleConfig.addVehicle("Base.pzkHMMV2", 37)
    PaintVehicleConfig.addVehicle("Base.pzkHMMV3", 37)
    PaintVehicleConfig.addVehicle("Base.pzkLimo", 37)
    PaintVehicleConfig.addVehicle("Base.pzkPickupFranklin", 33)
    PaintVehicleConfig.addVehicle("Base.pzkVanBox", 45)
    PaintVehicleConfig.addVehicle("Base.pzkPickUpTruckWoodboarded", 31)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTriumph", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinPony", 24)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierCeriseSedan", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashHellion", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashMayor", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashRapier", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTriumphTWD", 32)
    PaintVehicleConfig.addVehicle("Base.pzkCeriseStationWagon", 32)
    PaintVehicleConfig.addVehicle("Base.pzkDashMayorStationWagon", 32)
    PaintVehicleConfig.addVehicle("Base.pzkRapierStationWagon", 32)
    PaintVehicleConfig.addVehicle("Base.pzkTriumphStationWagon", 32)


    PaintVehicleConfig.addVehicle("Base.pzkDashRoyal", 30)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierDownhill", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashTornado", 30)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonLady", 32)
    PaintVehicleConfig.addVehicle("Base.pzkDashPhoenix", 32)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierE6", 32)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierF6", 32)

    PaintVehicleConfig.addVehicle("Base.pzkChevalierRoadrunner", 32)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonInitial", 32)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonXSR", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalSpirit", 27)
    PaintVehicleConfig.addVehicle("Base.pzkDashNoble", 27)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinStallion", 27)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinStallion2", 27)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinStallionSport", 27)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinIslander", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinHomelander", 32)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonCrown", 30)


    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckBed", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckShort", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckCab", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckBox", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckDump", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckFlatbed", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckPropane", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckRV", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTankerSeptic", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTankerWater", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTow", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckUtility", 40)

    PaintVehicleConfig.addVehicle("Base.pzkMinivanC22", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanChev", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanConvoy", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanMPV", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanT3", 35)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanT3C", 37)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanTask", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivan2", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMinivanPrev", 27)
    PaintVehicleConfig.addVehicle("Base.pzkVanMultivan", 37)

    PaintVehicleConfig.addVehicle("Base.pzkMastersonScout4D", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierPickupCrewLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierPickupCrewMedium", 35)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierProvince", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierProvinceLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierLaserModern", 30)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierE6Van", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierF6Van", 40)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierLaserOffroader", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFtypeTowTruck", 30)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierTowTruck", 30)
    PaintVehicleConfig.addVehicle("Base.pzkMerciaLangBerg", 40)
    PaintVehicleConfig.addVehicle("Base.pzkDashCheyene", 40)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalCruiser", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin350FWagonLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin350FPickupCrewLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin250FPickupWagonLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin250FPickupCrewLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin250FWagonLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin150van", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin150FPickupReg", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin150FWagonMedium", 35)
    PaintVehicleConfig.addVehicle("Base.pzkFranklin150FPickupMedium", 35)
    PaintVehicleConfig.addVehicle("Base.pzkDashIntruder250WagonLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkDashIntruder250PickupLong", 40)
    PaintVehicleConfig.addVehicle("Base.pzkDashIntruder150short", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashIntruder150RegVan", 30)

    PaintVehicleConfig.addVehicle("Base.pzkMastersonLadyZ", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashGTA", 30)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinStallionKing", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashRunner", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashPiranha", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashChampion", 30)
    PaintVehicleConfig.addVehicle("Base.pzkDashPhoenix80", 30)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierMaroca80", 30)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBug", 30)

    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckBed", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckShort", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckCab", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckBox", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckDump", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckFlatbed", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckGarbage", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckPropane", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckPropane2", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckRV", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTankerSeptic", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTankerWater", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckTow", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckUtility", 40)

    PaintVehicleConfig.addVehicle("Base.pzkFranklinTruckSemi", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFreightlinerFlat2", 40)
    PaintVehicleConfig.addVehicle("Base.pzkFreightlinerFlat", 40)
    PaintVehicleConfig.addVehicle("Base.pzkPeterbuiltSleeper", 40)
    PaintVehicleConfig.addVehicle("Base.pzkPeterbuilt", 40)

    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer330Sport", 31)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer3304D", 35)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer3302D", 31)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer534", 33)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer732", 35)
    PaintVehicleConfig.addVehicle("Base.pzkMerciaLang1240", 32)
    PaintVehicleConfig.addVehicle("Base.pzkMerciaLang12402D", 32)
    PaintVehicleConfig.addVehicle("Base.pzkMerciaLang4000Cabrio", 32)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalBayer330Cabrio", 31)
    PaintVehicleConfig.addVehicle("Base.pzkCarMuscleCabrio", 32)
    PaintVehicleConfig.addVehicle("Base.pzkDashRancherCabrio", 35)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierCosetteCabrio", 31)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonSunrise", 33)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonSensation", 33)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonExpander", 33)

    PaintVehicleConfig.addVehicle("Base.pzkTrailerCamping", 31)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalPfeiffer901", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalPfeiffer901c", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalPfeiffer930", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalPfeiffer930c", 27)

    PaintVehicleConfig.addVehicle("Base.pzkFranklinTriumphWagon", 29)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierCerise93", 27)
    PaintVehicleConfig.addVehicle("Base.pzkDashElite2D", 27)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonHarmonyWagon", 29)
    PaintVehicleConfig.addVehicle("Base.pzkMastersonHarmony", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalNord", 27)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalNordWagon", 29)
    PaintVehicleConfig.addVehicle("Base.pzkContinentalPyrenean310", 27)
    PaintVehicleConfig.addVehicle("Base.pzkChevalierCerise93Wagon", 29)

end