-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ct_oac_fixtures_counters_01_3"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_5"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_11"] = {{ name = "other", tiles = {"ct_oac_food_01_32", "ct_oac_food_01_34"} }, { name = "other", tiles = {"ct_oac_food_01_36", "ct_oac_food_01_38"} }, { name = "other", tiles = {"ct_oac_food_01_40", "ct_oac_food_01_42"} }, { name = "other", tiles = {"ct_oac_books&misc_01_32", "ct_oac_books&misc_01_34"} }, { name = "other", tiles = {"ct_oac_books&misc_01_36", "ct_oac_books&misc_01_38"} }}
overlayMap["ct_oac_fixtures_counters_01_13"] = {{ name = "other", tiles = {"ct_oac_food_01_33", "ct_oac_food_01_35"} }, { name = "other", tiles = {"ct_oac_food_01_37", "ct_oac_food_01_39"} }, { name = "other", tiles = {"ct_oac_food_01_41", "ct_oac_food_01_43"} }, { name = "other", tiles = {"ct_oac_books&misc_01_33", "ct_oac_books&misc_01_35"} }, { name = "other", tiles = {"ct_oac_books&misc_01_37", "ct_oac_books&misc_01_39"} }}
overlayMap["ct_oac_fixtures_counters_01_26"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_8", "ct_oac_books&misc_01_10"} }, { name = "other", tiles = {"ct_oac_food_01_12", "ct_oac_food_01_14"} }}
overlayMap["ct_oac_fixtures_counters_01_27"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_9", "ct_oac_books&misc_01_11"} }, { name = "other", tiles = {"ct_oac_food_01_13", "ct_oac_food_01_15"} }}
overlayMap["ct_oac_fixtures_counters_01_35"] = {{ name = "other", tiles = {"ct_oac_food_01_64", "ct_oac_food_01_66"} }, { name = "other", tiles = {"ct_oac_food_01_68", "ct_oac_food_01_70"} }, { name = "other", tiles = {"ct_oac_food_01_72", "ct_oac_food_01_74"} }, { name = "other", tiles = {"ct_oac_books&misc_01_48", "ct_oac_books&misc_01_50"} }, { name = "other", tiles = {"ct_oac_books&misc_01_52", "ct_oac_books&misc_01_54"} }}
overlayMap["ct_oac_fixtures_counters_01_37"] = {{ name = "other", tiles = {"ct_oac_food_01_65", "ct_oac_food_01_67"} }, { name = "other", tiles = {"ct_oac_food_01_69", "ct_oac_food_01_71"} }, { name = "other", tiles = {"ct_oac_food_01_73", "ct_oac_food_01_75"} }, { name = "other", tiles = {"ct_oac_books&misc_01_49", "ct_oac_books&misc_01_51"} }, { name = "other", tiles = {"ct_oac_books&misc_01_53", "ct_oac_books&misc_01_55"} }}
overlayMap["ct_oac_fixtures_counters_01_43"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_45"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_51"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_53"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_59"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_61"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_67"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_69"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_fixtures_counters_01_75"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_fixtures_counters_01_77"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_location_hospitality_sunstarmotel_02_13"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_location_hospitality_sunstarmotel_02_14"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_location_restaurant_bar_01_59"] = {{ name = "other", tiles = {"ct_oac_food_01_48", "ct_oac_food_01_50"} }, { name = "other", tiles = {"ct_oac_food_01_52", "ct_oac_food_01_54"} }, { name = "other", tiles = {"ct_oac_food_01_56", "ct_oac_food_01_58"} }, { name = "other", tiles = {"ct_oac_books&misc_01_40", "ct_oac_books&misc_01_42"} }, { name = "other", tiles = {"ct_oac_books&misc_01_44", "ct_oac_books&misc_01_46"} }}
overlayMap["ct_oac_location_restaurant_bar_01_61"] = {{ name = "other", tiles = {"ct_oac_food_01_49", "ct_oac_food_01_51"} }, { name = "other", tiles = {"ct_oac_food_01_53", "ct_oac_food_01_55"} }, { name = "other", tiles = {"ct_oac_food_01_57", "ct_oac_food_01_59"} }, { name = "other", tiles = {"ct_oac_books&misc_01_41", "ct_oac_books&misc_01_43"} }, { name = "other", tiles = {"ct_oac_books&misc_01_45", "ct_oac_books&misc_01_47"} }}
overlayMap["ct_oac_location_restaurant_seahorse_01_43"] = {{ name = "other", tiles = {"ct_oac_food_01_0", "ct_oac_food_01_2"} }, { name = "other", tiles = {"ct_oac_food_01_4", "ct_oac_food_01_6"} }, { name = "other", tiles = {"ct_oac_food_01_8", "ct_oac_food_01_10"} }, { name = "other", tiles = {"ct_oac_books&misc_01_0", "ct_oac_books&misc_01_2"} }, { name = "other", tiles = {"ct_oac_books&misc_01_4", "ct_oac_books&misc_01_6"} }}
overlayMap["ct_oac_location_restaurant_seahorse_01_45"] = {{ name = "other", tiles = {"ct_oac_food_01_1", "ct_oac_food_01_3"} }, { name = "other", tiles = {"ct_oac_food_01_5", "ct_oac_food_01_7"} }, { name = "other", tiles = {"ct_oac_food_01_9", "ct_oac_food_01_11"} }, { name = "other", tiles = {"ct_oac_books&misc_01_1", "ct_oac_books&misc_01_3"} }, { name = "other", tiles = {"ct_oac_books&misc_01_5", "ct_oac_books&misc_01_7"} }}
overlayMap["ct_oac_location_trailer_02_18"] = {{ name = "other", tiles = {"ct_oac_food_01_16", "ct_oac_food_01_18"} }, { name = "other", tiles = {"ct_oac_food_01_20", "ct_oac_food_01_22"} }, { name = "other", tiles = {"ct_oac_food_01_24", "ct_oac_food_01_26"} }, { name = "other", tiles = {"ct_oac_books&misc_01_16", "ct_oac_books&misc_01_18"} }, { name = "other", tiles = {"ct_oac_books&misc_01_20", "ct_oac_books&misc_01_22"} }}
overlayMap["ct_oac_location_trailer_02_19"] = {{ name = "other", tiles = {"ct_oac_food_01_17", "ct_oac_food_01_19"} }, { name = "other", tiles = {"ct_oac_food_01_21", "ct_oac_food_01_23"} }, { name = "other", tiles = {"ct_oac_food_01_25", "ct_oac_food_01_27"} }, { name = "other", tiles = {"ct_oac_books&misc_01_17", "ct_oac_books&misc_01_19"} }, { name = "other", tiles = {"ct_oac_books&misc_01_21", "ct_oac_books&misc_01_23"} }}
overlayMap["ct_oac_location_trailer_02_22"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_24", "ct_oac_books&misc_01_26"} }, { name = "other", tiles = {"ct_oac_food_01_28", "ct_oac_food_01_30"} }}
overlayMap["ct_oac_location_trailer_02_23"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_25", "ct_oac_books&misc_01_27"} }, { name = "other", tiles = {"ct_oac_food_01_29", "ct_oac_food_01_31"} }}
--overlayMap["ct_oac_furniture_storage_01_0"]
overlayMap["ct_oac_furniture_storage_01_1"] = {{ name = "other", tiles = {"ct_oac_clothing_01_1", "ct_oac_clothing_01_5"} }}
overlayMap["ct_oac_furniture_storage_01_2"] = {{ name = "other", tiles = {"ct_oac_clothing_01_2", "ct_oac_clothing_01_6"} }}
--overlayMap["ct_oac_furniture_storage_01_3"]
overlayMap["ct_oac_furniture_storage_01_8"] = {{ name = "other", tiles = {"ct_oac_clothing_01_8"} }}
overlayMap["ct_oac_furniture_storage_01_9"] = {{ name = "other", tiles = {"ct_oac_clothing_01_9"} }}
overlayMap["ct_oac_furniture_storage_01_10"] = {{ name = "other", tiles = {"ct_oac_clothing_01_10"} }}
overlayMap["ct_oac_furniture_storage_01_11"] = {{ name = "other", tiles = {"ct_oac_clothing_01_11"} }}
overlayMap["ct_oac_furniture_storage_01_12"] = {{ name = "other", tiles = {"ct_oac_clothing_01_12"} }}
overlayMap["ct_oac_furniture_storage_01_15"] = {{ name = "other", tiles = {"ct_oac_clothing_01_15"} }}
overlayMap["ct_oac_furniture_storage_01_16"] = {{ name = "other", tiles = {"ct_oac_clothing_01_16"} }}
overlayMap["ct_oac_furniture_storage_01_17"] = {{ name = "other", tiles = {"ct_oac_clothing_01_17"} }}
overlayMap["ct_oac_furniture_storage_01_18"] = {{ name = "other", tiles = {"ct_oac_clothing_01_18"} }}
overlayMap["ct_oac_furniture_storage_01_19"] = {{ name = "other", tiles = {"ct_oac_clothing_01_19"} }}
overlayMap["ct_oac_furniture_storage_01_20"] = {{ name = "other", tiles = {"ct_oac_clothing_01_20"} }}
overlayMap["ct_oac_furniture_storage_01_23"] = {{ name = "other", tiles = {"ct_oac_clothing_01_23"} }}
overlayMap["ct_oac_furniture_storage_01_24"] = {{ name = "other", tiles = {"ct_oac_clothing_01_24", "ct_oac_clothing_01_26"} }}
overlayMap["ct_oac_furniture_storage_01_25"] = {{ name = "other", tiles = {"ct_oac_clothing_01_25", "ct_oac_clothing_01_27"} }}
overlayMap["ct_oac_furniture_storage_01_26"] = {{ name = "other", tiles = {"ct_oac_clothing_01_28", "ct_oac_clothing_01_30"} }}
overlayMap["ct_oac_furniture_storage_01_27"] = {{ name = "other", tiles = {"ct_oac_clothing_01_29", "ct_oac_clothing_01_31"} }}
overlayMap["ct_oac_furniture_storage_01_28"] = {{ name = "other", tiles = {"ct_oac_clothing_01_32", "ct_oac_clothing_01_34"} }}
overlayMap["ct_oac_furniture_storage_01_29"] = {{ name = "other", tiles = {"ct_oac_clothing_01_33", "ct_oac_clothing_01_35"} }}
overlayMap["ct_oac_furniture_storage_01_30"] = {{ name = "other", tiles = {"ct_oac_clothing_01_36"} }}
overlayMap["ct_oac_furniture_storage_01_31"] = {{ name = "other", tiles = {"ct_oac_clothing_01_37"} }}
overlayMap["ct_oac_furniture_storage_01_32"] = {{ name = "other", tiles = {"ct_oac_clothing_01_40", "ct_oac_clothing_01_42"} }}
overlayMap["ct_oac_furniture_storage_01_33"] = {{ name = "other", tiles = {"ct_oac_clothing_01_41", "ct_oac_clothing_01_43"} }}
overlayMap["ct_oac_furniture_storage_01_34"] = {{ name = "other", tiles = {"ct_oac_clothing_01_44"} }}
overlayMap["ct_oac_furniture_storage_01_35"] = {{ name = "other", tiles = {"ct_oac_clothing_01_45"} }}
overlayMap["ct_oac_furniture_storage_01_36"] = {{ name = "other", tiles = {"ct_oac_clothing_01_24", "ct_oac_clothing_01_26"} }}
overlayMap["ct_oac_furniture_storage_01_37"] = {{ name = "other", tiles = {"ct_oac_clothing_01_25", "ct_oac_clothing_01_27"} }}
overlayMap["ct_oac_furniture_storage_01_38"] = {{ name = "other", tiles = {"ct_oac_clothing_01_28", "ct_oac_clothing_01_30"} }}
overlayMap["ct_oac_furniture_storage_01_39"] = {{ name = "other", tiles = {"ct_oac_clothing_01_29", "ct_oac_clothing_01_31"} }}
overlayMap["ct_oac_furniture_storage_01_40"] = {{ name = "other", tiles = {"ct_oac_clothing_01_32", "ct_oac_clothing_01_34"} }}
overlayMap["ct_oac_furniture_storage_01_41"] = {{ name = "other", tiles = {"ct_oac_clothing_01_33", "ct_oac_clothing_01_35"} }}
overlayMap["ct_oac_furniture_storage_01_42"] = {{ name = "other", tiles = {"ct_oac_clothing_01_36"} }}
overlayMap["ct_oac_furniture_storage_01_43"] = {{ name = "other", tiles = {"ct_oac_clothing_01_37"} }}
overlayMap["ct_oac_furniture_storage_01_44"] = {{ name = "other", tiles = {"ct_oac_clothing_01_40", "ct_oac_clothing_01_42"} }}
overlayMap["ct_oac_furniture_storage_01_45"] = {{ name = "other", tiles = {"ct_oac_clothing_01_41", "ct_oac_clothing_01_43"} }}
overlayMap["ct_oac_furniture_storage_01_46"] = {{ name = "other", tiles = {"ct_oac_clothing_01_44"} }}
overlayMap["ct_oac_furniture_storage_01_47"] = {{ name = "other", tiles = {"ct_oac_clothing_01_45"} }}
--overlayMap["ct_oac_furniture_storage_01_48"]
overlayMap["ct_oac_furniture_storage_01_49"] = {{ name = "other", tiles = {"ct_oac_clothing_01_1", "ct_oac_clothing_01_5"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_49", "ct_oac_clothing_01_53"} }--]]}
overlayMap["ct_oac_furniture_storage_01_50"] = {{ name = "other", tiles = {"ct_oac_clothing_01_2", "ct_oac_clothing_01_6"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_50", "ct_oac_clothing_01_54"} }--]]}
--overlayMap["ct_oac_furniture_storage_01_51"]
overlayMap["ct_oac_furniture_storage_01_56"] = {{ name = "other", tiles = {"ct_oac_clothing_01_8"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_56"} }--]]}
overlayMap["ct_oac_furniture_storage_01_57"] = {{ name = "other", tiles = {"ct_oac_clothing_01_9"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_57"} }--]]}
overlayMap["ct_oac_furniture_storage_01_58"] = {{ name = "other", tiles = {"ct_oac_clothing_01_10"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_58"} }--]]}
overlayMap["ct_oac_furniture_storage_01_59"] = {{ name = "other", tiles = {"ct_oac_clothing_01_11"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_59"} }--]]}
overlayMap["ct_oac_furniture_storage_01_60"] = {{ name = "other", tiles = {"ct_oac_clothing_01_12"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_60"} }--]]}
overlayMap["ct_oac_furniture_storage_01_63"] = {{ name = "other", tiles = {"ct_oac_clothing_01_15"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_63"} }--]]}
overlayMap["ct_oac_furniture_storage_01_64"] = {{ name = "other", tiles = {"ct_oac_clothing_01_16"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_64"} }--]]}
overlayMap["ct_oac_furniture_storage_01_65"] = {{ name = "other", tiles = {"ct_oac_clothing_01_17"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_65"} }--]]}
overlayMap["ct_oac_furniture_storage_01_66"] = {{ name = "other", tiles = {"ct_oac_clothing_01_18"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_66"} }--]]}
overlayMap["ct_oac_furniture_storage_01_67"] = {{ name = "other", tiles = {"ct_oac_clothing_01_19"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_67"} }--]]}
overlayMap["ct_oac_furniture_storage_01_68"] = {{ name = "other", tiles = {"ct_oac_clothing_01_20"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_68"} }--]]}
overlayMap["ct_oac_furniture_storage_01_71"] = {{ name = "other", tiles = {"ct_oac_clothing_01_23"} }--[[, { name = "other", tiles = {"ct_oac_clothing_01_71"} }--]]}
--overlayMap["ct_oac_furniture_storage_01_72"]
overlayMap["ct_oac_furniture_storage_01_73"] = {{ name = "other", tiles = {"ct_oac_clothing_01_73", "ct_oac_clothing_01_77"} }}
overlayMap["ct_oac_furniture_storage_01_74"] = {{ name = "other", tiles = {"ct_oac_clothing_01_74", "ct_oac_clothing_01_78"} }}
--overlayMap["ct_oac_furniture_storage_01_75"]
overlayMap["ct_oac_furniture_storage_01_80"] = {{ name = "other", tiles = {"ct_oac_clothing_01_80", "ct_oac_clothing_01_82"} }}
overlayMap["ct_oac_furniture_storage_01_81"] = {{ name = "other", tiles = {"ct_oac_clothing_01_81", "ct_oac_clothing_01_83"} }}
overlayMap["ct_oac_furniture_storage_01_82"] = {{ name = "other", tiles = {"ct_oac_clothing_01_84", "ct_oac_clothing_01_86"} }}
overlayMap["ct_oac_furniture_storage_01_83"] = {{ name = "other", tiles = {"ct_oac_clothing_01_85", "ct_oac_clothing_01_87"} }}
overlayMap["ct_oac_furniture_storage_01_84"] = {{ name = "other", tiles = {"ct_oac_clothing_01_88", "ct_oac_clothing_01_90"} }}
overlayMap["ct_oac_furniture_storage_01_85"] = {{ name = "other", tiles = {"ct_oac_clothing_01_89", "ct_oac_clothing_01_91"} }}
overlayMap["ct_oac_furniture_storage_01_86"] = {{ name = "other", tiles = {"ct_oac_clothing_01_92"} }}
overlayMap["ct_oac_furniture_storage_01_87"] = {{ name = "other", tiles = {"ct_oac_clothing_01_93"} }}
--overlayMap["ct_oac_furniture_storage_01_88"]
overlayMap["ct_oac_furniture_storage_01_89"] = {{ name = "other", tiles = {"ct_oac_clothing_01_97", "ct_oac_clothing_01_101"} }}
overlayMap["ct_oac_furniture_storage_01_90"] = {{ name = "other", tiles = {"ct_oac_clothing_01_98", "ct_oac_clothing_01_102"} }}
--overlayMap["ct_oac_furniture_storage_01_91"]
overlayMap["ct_oac_furniture_storage_01_96"] = {{ name = "other", tiles = {"ct_oac_clothing_01_104"} }}
overlayMap["ct_oac_furniture_storage_01_97"] = {{ name = "other", tiles = {"ct_oac_clothing_01_105"} }}
overlayMap["ct_oac_furniture_storage_01_98"] = {{ name = "other", tiles = {"ct_oac_clothing_01_106"} }}
overlayMap["ct_oac_furniture_storage_01_99"] = {{ name = "other", tiles = {"ct_oac_clothing_01_107"} }}
overlayMap["ct_oac_furniture_storage_01_100"] = {{ name = "other", tiles = {"ct_oac_clothing_01_108"} }}
overlayMap["ct_oac_furniture_storage_01_103"] = {{ name = "other", tiles = {"ct_oac_clothing_01_111"} }}
overlayMap["ct_oac_furniture_storage_01_104"] = {{ name = "other", tiles = {"ct_oac_clothing_01_140", "ct_oac_clothing_01_142"} }}
overlayMap["ct_oac_furniture_storage_01_105"] = {{ name = "other", tiles = {"ct_oac_clothing_01_141", "ct_oac_clothing_01_143"} }}
overlayMap["ct_oac_furniture_storage_01_106"] = {{ name = "other", tiles = {"ct_oac_clothing_01_136", "ct_oac_clothing_01_138"} }}
overlayMap["ct_oac_furniture_storage_01_107"] = {{ name = "other", tiles = {"ct_oac_clothing_01_137", "ct_oac_clothing_01_139"} }}
overlayMap["ct_oac_furniture_storage_01_108"] = {{ name = "other", tiles = {"ct_oac_clothing_01_148"} }}
overlayMap["ct_oac_furniture_storage_01_109"] = {{ name = "other", tiles = {"ct_oac_clothing_01_149"} }}
overlayMap["ct_oac_furniture_storage_01_110"] = {{ name = "other", tiles = {"ct_oac_clothing_01_144", "ct_oac_clothing_01_146"} }}
overlayMap["ct_oac_furniture_storage_01_111"] = {{ name = "other", tiles = {"ct_oac_clothing_01_145", "ct_oac_clothing_01_147"} }}
overlayMap["ct_oac_furniture_storage_01_112"] = {{ name = "other", tiles = {"ct_oac_clothing_01_156"} }}
overlayMap["ct_oac_furniture_storage_01_113"] = {{ name = "other", tiles = {"ct_oac_clothing_01_157"} }}
overlayMap["ct_oac_furniture_storage_01_114"] = {{ name = "other", tiles = {"ct_oac_clothing_01_152", "ct_oac_clothing_01_154"} }}
overlayMap["ct_oac_furniture_storage_01_115"] = {{ name = "other", tiles = {"ct_oac_clothing_01_153", "ct_oac_clothing_01_155"} }}
overlayMap["ct_oac_furniture_storage_01_116"] = {{ name = "other", tiles = {"ct_oac_clothing_01_140", "ct_oac_clothing_01_142"} }}
overlayMap["ct_oac_furniture_storage_01_117"] = {{ name = "other", tiles = {"ct_oac_clothing_01_141", "ct_oac_clothing_01_143"} }}
overlayMap["ct_oac_furniture_storage_01_118"] = {{ name = "other", tiles = {"ct_oac_clothing_01_136", "ct_oac_clothing_01_138"} }}
overlayMap["ct_oac_furniture_storage_01_119"] = {{ name = "other", tiles = {"ct_oac_clothing_01_137", "ct_oac_clothing_01_139"} }}
overlayMap["ct_oac_furniture_storage_01_120"] = {{ name = "other", tiles = {"ct_oac_clothing_01_148"} }}
overlayMap["ct_oac_furniture_storage_01_121"] = {{ name = "other", tiles = {"ct_oac_clothing_01_149"} }}
overlayMap["ct_oac_furniture_storage_01_122"] = {{ name = "other", tiles = {"ct_oac_clothing_01_144", "ct_oac_clothing_01_146"} }}
overlayMap["ct_oac_furniture_storage_01_123"] = {{ name = "other", tiles = {"ct_oac_clothing_01_145", "ct_oac_clothing_01_147"} }}
overlayMap["ct_oac_furniture_storage_01_124"] = {{ name = "other", tiles = {"ct_oac_clothing_01_156"} }}
overlayMap["ct_oac_furniture_storage_01_125"] = {{ name = "other", tiles = {"ct_oac_clothing_01_157"} }}
overlayMap["ct_oac_furniture_storage_01_126"] = {{ name = "other", tiles = {"ct_oac_clothing_01_152", "ct_oac_clothing_01_154"} }}
overlayMap["ct_oac_furniture_storage_01_127"] = {{ name = "other", tiles = {"ct_oac_clothing_01_153", "ct_oac_clothing_01_155"} }}
overlayMap["ct_oac_furniture_storage_01_128"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_56", "ct_oac_books&misc_01_60"} }, { name = "other", tiles = {"ct_oac_books&misc_01_80", "ct_oac_books&misc_01_84"} }, { name = "other", tiles = {"ct_oac_weapons_01_72", "ct_oac_weapons_01_76"} }}
overlayMap["ct_oac_furniture_storage_01_129"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_57", "ct_oac_books&misc_01_61"} }, { name = "other", tiles = {"ct_oac_books&misc_01_81", "ct_oac_books&misc_01_85"} }, { name = "other", tiles = {"ct_oac_weapons_01_73", "ct_oac_weapons_01_77"} }}
overlayMap["ct_oac_furniture_storage_01_130"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_58", "ct_oac_books&misc_01_62"} }, { name = "other", tiles = {"ct_oac_books&misc_01_82", "ct_oac_books&misc_01_86"} }, { name = "other", tiles = {"ct_oac_weapons_01_74", "ct_oac_weapons_01_78"} }}
overlayMap["ct_oac_furniture_storage_01_131"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_59", "ct_oac_books&misc_01_63"} }, { name = "other", tiles = {"ct_oac_books&misc_01_83", "ct_oac_books&misc_01_87"} }, { name = "other", tiles = {"ct_oac_weapons_01_75", "ct_oac_weapons_01_79"} }}
--overlayMap["ct_oac_furniture_storage_01_132"]
--overlayMap["ct_oac_furniture_storage_01_133"]
--overlayMap["ct_oac_furniture_storage_01_136"]
overlayMap["ct_oac_furniture_storage_01_137"] = {{ name = "other", tiles = {"ct_oac_clothing_01_113", "ct_oac_clothing_01_117"} }}
overlayMap["ct_oac_furniture_storage_01_138"] = {{ name = "other", tiles = {"ct_oac_clothing_01_114", "ct_oac_clothing_01_118"} }}
--overlayMap["ct_oac_furniture_storage_01_139"]
overlayMap["ct_oac_furniture_storage_01_144"] = {{ name = "other", tiles = {"ct_oac_clothing_01_120"} }}
overlayMap["ct_oac_furniture_storage_01_145"] = {{ name = "other", tiles = {"ct_oac_clothing_01_121"} }}
overlayMap["ct_oac_furniture_storage_01_146"] = {{ name = "other", tiles = {"ct_oac_clothing_01_122"} }}
overlayMap["ct_oac_furniture_storage_01_147"] = {{ name = "other", tiles = {"ct_oac_clothing_01_123"} }}
overlayMap["ct_oac_furniture_storage_01_148"] = {{ name = "other", tiles = {"ct_oac_clothing_01_124"} }}
overlayMap["ct_oac_furniture_storage_01_151"] = {{ name = "other", tiles = {"ct_oac_clothing_01_127"} }}
overlayMap["ct_oac_furniture_storage_01_152"] = {{ name = "other", tiles = {"ct_oac_clothing_01_128"} }}
overlayMap["ct_oac_furniture_storage_01_153"] = {{ name = "other", tiles = {"ct_oac_clothing_01_129"} }}
overlayMap["ct_oac_furniture_storage_01_154"] = {{ name = "other", tiles = {"ct_oac_clothing_01_130"} }}
overlayMap["ct_oac_furniture_storage_01_155"] = {{ name = "other", tiles = {"ct_oac_clothing_01_131"} }}
overlayMap["ct_oac_furniture_storage_01_156"] = {{ name = "other", tiles = {"ct_oac_clothing_01_132"} }}
overlayMap["ct_oac_furniture_storage_01_159"] = {{ name = "other", tiles = {"ct_oac_clothing_01_135"} }}
overlayMap["ct_oac_furniture_storage_01_160"] = {{ name = "other", tiles = {"ct_oac_clothing_01_140", "ct_oac_clothing_01_142"} }}
overlayMap["ct_oac_furniture_storage_01_161"] = {{ name = "other", tiles = {"ct_oac_clothing_01_141", "ct_oac_clothing_01_143"} }}
overlayMap["ct_oac_furniture_storage_01_162"] = {{ name = "other", tiles = {"ct_oac_clothing_01_136", "ct_oac_clothing_01_138"} }}
overlayMap["ct_oac_furniture_storage_01_163"] = {{ name = "other", tiles = {"ct_oac_clothing_01_137", "ct_oac_clothing_01_139"} }}
overlayMap["ct_oac_furniture_storage_01_164"] = {{ name = "other", tiles = {"ct_oac_clothing_01_148"} }}
overlayMap["ct_oac_furniture_storage_01_165"] = {{ name = "other", tiles = {"ct_oac_clothing_01_149"} }}
overlayMap["ct_oac_furniture_storage_01_166"] = {{ name = "other", tiles = {"ct_oac_clothing_01_144", "ct_oac_clothing_01_146"} }}
overlayMap["ct_oac_furniture_storage_01_167"] = {{ name = "other", tiles = {"ct_oac_clothing_01_145", "ct_oac_clothing_01_147"} }}
overlayMap["ct_oac_furniture_storage_01_168"] = {{ name = "other", tiles = {"ct_oac_clothing_01_156"} }}
overlayMap["ct_oac_furniture_storage_01_169"] = {{ name = "other", tiles = {"ct_oac_clothing_01_157"} }}
overlayMap["ct_oac_furniture_storage_01_170"] = {{ name = "other", tiles = {"ct_oac_clothing_01_152", "ct_oac_clothing_01_154"} }}
overlayMap["ct_oac_furniture_storage_01_171"] = {{ name = "other", tiles = {"ct_oac_clothing_01_153", "ct_oac_clothing_01_155"} }}
overlayMap["ct_oac_fixtures_bathroom_01_28"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_64", "ct_oac_books&misc_01_66"} }}
overlayMap["ct_oac_fixtures_bathroom_01_29"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_65", "ct_oac_books&misc_01_67"} }}
overlayMap["ct_oac_furniture_storage_02_0"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_88", "ct_oac_books&misc_01_90"} }}
overlayMap["ct_oac_furniture_storage_02_1"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_89", "ct_oac_books&misc_01_91"} }}
--overlayMap["ct_oac_furniture_storage_02_4"]
overlayMap["ct_oac_furniture_storage_02_8"] = {{ name = "other", tiles = {"ct_oac_weapons_01_0", "ct_oac_weapons_01_2"} }, { name = "other", tiles = {"ct_oac_weapons_01_4", "ct_oac_weapons_01_6"} }, { name = "other", tiles = {"ct_oac_weapons_01_8", "ct_oac_weapons_01_10"} }, { name = "other", tiles = {"ct_oac_weapons_01_12", "ct_oac_weapons_01_14"} }, { name = "other", tiles = {"ct_oac_weapons_01_16", "ct_oac_weapons_01_18"} }}
overlayMap["ct_oac_furniture_storage_02_9"] = {{ name = "other", tiles = {"ct_oac_weapons_01_1", "ct_oac_weapons_01_3"} }, { name = "other", tiles = {"ct_oac_weapons_01_5", "ct_oac_weapons_01_7"} }, { name = "other", tiles = {"ct_oac_weapons_01_9", "ct_oac_weapons_01_11"} }, { name = "other", tiles = {"ct_oac_weapons_01_13", "ct_oac_weapons_01_15"} }, { name = "other", tiles = {"ct_oac_weapons_01_17", "ct_oac_weapons_01_19"} }}
--overlayMap["ct_oac_furniture_storage_02_12"]
--overlayMap["ct_oac_furniture_storage_02_16"]
--overlayMap["ct_oac_furniture_storage_02_17"]
--overlayMap["ct_oac_furniture_storage_02_18"]
--overlayMap["ct_oac_furniture_storage_02_19"]
--overlayMap["ct_oac_furniture_storage_02_20"]
overlayMap["ct_oac_furniture_storage_02_28"] = {{ name = "other", tiles = {"ct_oac_weapons_01_80", "ct_oac_weapons_01_84"} }}
overlayMap["ct_oac_furniture_storage_02_29"] = {{ name = "other", tiles = {"ct_oac_weapons_01_81", "ct_oac_weapons_01_85"} }}
overlayMap["ct_oac_furniture_storage_02_30"] = {{ name = "other", tiles = {"ct_oac_weapons_01_82", "ct_oac_weapons_01_86"} }}
overlayMap["ct_oac_furniture_storage_02_31"] = {{ name = "other", tiles = {"ct_oac_weapons_01_83", "ct_oac_weapons_01_87"} }}
--overlayMap["ct_oac_furniture_storage_02_32"]
--overlayMap["ct_oac_furniture_storage_02_33"]
--overlayMap["ct_oac_furniture_storage_02_34"]
--overlayMap["ct_oac_furniture_storage_02_35"]
--overlayMap["ct_oac_furniture_storage_02_40"]
overlayMap["ct_oac_furniture_storage_02_41"] = {{ name = "other", tiles = {"ct_oac_clothing_01_161", "ct_oac_clothing_01_165"} }}
overlayMap["ct_oac_furniture_storage_02_42"] = {{ name = "other", tiles = {"ct_oac_clothing_01_162", "ct_oac_clothing_01_166"} }}
--overlayMap["ct_oac_furniture_storage_02_43"]
--overlayMap["ct_oac_furniture_storage_02_52"]
--overlayMap["ct_oac_furniture_storage_02_56"]
--overlayMap["ct_oac_furniture_storage_02_57"]
--overlayMap["ct_oac_furniture_storage_02_58"]
--overlayMap["ct_oac_furniture_storage_02_59"]
--overlayMap["ct_oac_furniture_storage_02_64"]
--overlayMap["ct_oac_furniture_storage_02_65"]
--overlayMap["ct_oac_furniture_storage_02_66"]
--overlayMap["ct_oac_furniture_storage_02_67"]
--overlayMap["ct_oac_furniture_storage_02_72"]
--overlayMap["ct_oac_furniture_storage_02_73"]
--overlayMap["ct_oac_furniture_storage_02_74"]
--overlayMap["ct_oac_furniture_storage_02_75"]
--overlayMap["ct_oac_furniture_storage_02_80"]
--overlayMap["ct_oac_furniture_storage_02_81"]
--overlayMap["ct_oac_furniture_storage_02_82"]
--overlayMap["ct_oac_furniture_storage_02_83"]
--overlayMap["ct_oac_furniture_storage_02_88"]
--overlayMap["ct_oac_furniture_storage_02_89"]
--overlayMap["ct_oac_furniture_storage_02_90"]
--overlayMap["ct_oac_furniture_storage_02_91"]
--overlayMap["ct_oac_location_business_machinery_01_28"]
--overlayMap["ct_oac_location_business_machinery_01_29"]
--overlayMap["ct_oac_location_business_machinery_01_30"]
--overlayMap["ct_oac_location_business_machinery_01_31"]
--overlayMap["ct_oac_location_business_machinery_01_32"]
--overlayMap["ct_oac_location_business_machinery_01_33"]
--overlayMap["ct_oac_location_business_machinery_01_34"]
--overlayMap["ct_oac_location_business_machinery_01_35"]
--overlayMap["ct_oac_location_business_machinery_01_36"]
--overlayMap["ct_oac_location_business_machinery_01_37"]
--overlayMap["ct_oac_location_business_machinery_01_38"]
--overlayMap["ct_oac_location_business_machinery_01_39"]
--OfficeDesk
--DarkOfficeDesk
--MedicalToolDrawers
--FirstAid
--MedicalCabinetWide
overlayMap["ct_oac_location_military_generic_01_22"] = {{ name = "other", tiles = {"ct_oac_weapons_01_24", "ct_oac_weapons_01_26"} }, { name = "other", tiles = {"ct_oac_weapons_01_28", "ct_oac_weapons_01_30"} }, { name = "other", tiles = {"ct_oac_weapons_01_32", "ct_oac_weapons_01_34"} }, { name = "other", tiles = {"ct_oac_weapons_01_36", "ct_oac_weapons_01_38"} }, { name = "other", tiles = {"ct_oac_weapons_01_40", "ct_oac_weapons_01_42"} }}
overlayMap["ct_oac_location_military_generic_01_23"] = {{ name = "other", tiles = {"ct_oac_weapons_01_25", "ct_oac_weapons_01_27"} }, { name = "other", tiles = {"ct_oac_weapons_01_29", "ct_oac_weapons_01_31"} }, { name = "other", tiles = {"ct_oac_weapons_01_33", "ct_oac_weapons_01_35"} }, { name = "other", tiles = {"ct_oac_weapons_01_37", "ct_oac_weapons_01_39"} }, { name = "other", tiles = {"ct_oac_weapons_01_41", "ct_oac_weapons_01_43"} }}
overlayMap["ct_oac_location_military_generic_01_20"] = {{ name = "other", tiles = {"ct_oac_weapons_01_48", "ct_oac_weapons_01_50"} }, { name = "other", tiles = {"ct_oac_weapons_01_52", "ct_oac_weapons_01_54"} }, { name = "other", tiles = {"ct_oac_weapons_01_56", "ct_oac_weapons_01_58"} }, { name = "other", tiles = {"ct_oac_weapons_01_60", "ct_oac_weapons_01_62"} }, { name = "other", tiles = {"ct_oac_weapons_01_64", "ct_oac_weapons_01_66"} }}
overlayMap["ct_oac_location_military_generic_01_21"] = {{ name = "other", tiles = {"ct_oac_weapons_01_49", "ct_oac_weapons_01_51"} }, { name = "other", tiles = {"ct_oac_weapons_01_53", "ct_oac_weapons_01_55"} }, { name = "other", tiles = {"ct_oac_weapons_01_57", "ct_oac_weapons_01_59"} }, { name = "other", tiles = {"ct_oac_weapons_01_61", "ct_oac_weapons_01_63"} }, { name = "other", tiles = {"ct_oac_weapons_01_65", "ct_oac_weapons_01_67"} }}
overlayMap["ct_oac_trashcontainers_01_0"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_0", "ct_oac_trash&junk_01_1"} }, { name = "other", tiles = {"ct_oac_trash&junk_01_8", "ct_oac_trash&junk_01_9"} }}
overlayMap["ct_oac_trashcontainers_01_1"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_2", "ct_oac_trash&junk_01_3"} }, { name = "other", tiles = {"ct_oac_trash&junk_01_10", "ct_oac_trash&junk_01_11"} }}
overlayMap["ct_oac_trashcontainers_01_2"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_4", "ct_oac_trash&junk_01_5"} }, { name = "other", tiles = {"ct_oac_trash&junk_01_12", "ct_oac_trash&junk_01_13"} }}
overlayMap["ct_oac_trashcontainers_01_3"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_6", "ct_oac_trash&junk_01_7"} }, { name = "other", tiles = {"ct_oac_trash&junk_01_14", "ct_oac_trash&junk_01_15"} }}
overlayMap["ct_oac_trashcontainers_01_8"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_16", "ct_oac_trash&junk_01_17"} }}
overlayMap["ct_oac_trashcontainers_01_9"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_18", "ct_oac_trash&junk_01_19"} }}
overlayMap["ct_oac_trashcontainers_01_10"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_20", "ct_oac_trash&junk_01_21"} }}
overlayMap["ct_oac_trashcontainers_01_11"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_22", "ct_oac_trash&junk_01_23"} }}
overlayMap["ct_oac_trashcontainers_01_12"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_32", "ct_oac_trash&junk_01_33"} }}
overlayMap["ct_oac_trashcontainers_01_13"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_34", "ct_oac_trash&junk_01_35"} }}
overlayMap["ct_oac_trashcontainers_01_14"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_36", "ct_oac_trash&junk_01_37"} }}
overlayMap["ct_oac_trashcontainers_01_15"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_38", "ct_oac_trash&junk_01_39"} }}
overlayMap["ct_oac_trashcontainers_01_16"] = {{ name = "other", tiles = {"ct_oac_trash&junk_01_48", "ct_oac_trash&junk_01_49"} }, { name = "other", tiles = {"ct_oac_trash&junk_01_50", "ct_oac_trash&junk_01_51"} }}
overlayMap["ct_oac_trashcontainers_01_24"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_72", "ct_oac_books&misc_01_74"} }}
overlayMap["ct_oac_trashcontainers_01_25"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_73", "ct_oac_books&misc_01_75"} }}
overlayMap["ct_oac_trashcontainers_01_26"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_76", "ct_oac_books&misc_01_78"} }}
overlayMap["ct_oac_trashcontainers_01_27"] = {{ name = "other", tiles = {"ct_oac_books&misc_01_77", "ct_oac_books&misc_01_79"} }}
-- ------------------------------------------------------------------------------------------------
--Compatibility with "Post Flag" mod
overlayMap["ct_oac_street_decoration_01_24"] = {{ name = "other", tiles = {"ct_oac_street_decoration_01_28"} }}
overlayMap["ct_oac_street_decoration_01_25"] = {{ name = "other", tiles = {"ct_oac_street_decoration_01_29"} }}
overlayMap["ct_oac_street_decoration_01_26"] = {{ name = "other", tiles = {"ct_oac_street_decoration_01_30"} }}
overlayMap["ct_oac_street_decoration_01_27"] = {{ name = "other", tiles = {"ct_oac_street_decoration_01_31"} }}
overlayMap["damaged_objects_01_18"] = {{ name = "other", tiles = {""} }}
overlayMap["damaged_objects_01_19"] = {{ name = "other", tiles = {""} }}
overlayMap["damaged_objects_01_20"] = {{ name = "other", tiles = {""} }}
overlayMap["damaged_objects_01_21"] = {{ name = "other", tiles = {""} }}
-- ------------------------------------------------------------------------------------------------
overlayMap["damaged_objects_01_12"] = {{ name = "other", tiles = {""} }}
overlayMap["damaged_objects_01_13"] = {{ name = "other", tiles = {""} }}
overlayMap["damaged_objects_01_14"] = {{ name = "other", tiles = {""} }}
-- ------------------------------------------------------------------------------------------------
--Compatibility with "More Damaged Objects" mod
overlayMap["ct_more_damaged_objects_01_16"] = {{ name = "other", tiles = {""} }}
overlayMap["ct_more_damaged_objects_01_17"] = {{ name = "other", tiles = {""} }}
overlayMap["ct_more_damaged_objects_01_18"] = {{ name = "other", tiles = {""} }}
overlayMap["ct_more_damaged_objects_01_19"] = {{ name = "other", tiles = {""} }}
-- ------------------------------------------------------------------------------------------------

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap