require 'Items/ProceduralDistributions'
require "Items/ItemPicker"

-- Barrel
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_TAB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_CSB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_CFWSB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_ATSB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_TTAB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_CCB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Canon
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_Beowulf");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_sr_s");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_XDZT");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_1911");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_kac");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_CARVER");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_109");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_MK18");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_4guan");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AACMini7_Silencer");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_fang1_Silencer");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_baoguo");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_kac");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_fang");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_M4MK18");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_pomen");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_CCB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QG_CSB");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.VP09");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M82_cat_muzzle");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_SnipeX");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.FortisNitride_RED2");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.kriss_muzzle_d_Silencer");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M82_cat_Silencer");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.SMSUP_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AR15_slience");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_OF");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Grip
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.WB_SST");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.TshiftGrip");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.SE-5Grip");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AFG_Blk");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ASh-12_Grip");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.WB_xie");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.CobraGrip");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HeraCQR_Grip");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- L_Scope
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ThermalImaging_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HeartbeatSensor");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HeartbeatSensorPlus");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AmmoPD");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Laser
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.DBAL_9021_Bottom");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.DBAL77Laser_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.PEQ_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Light
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ArmytekPredator_Bottom");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ArmytekPredator_Bottom2");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- R_Scope
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.leupold");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.G33_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Scope
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.MZ_RMR");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.MZ_paoduijing");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.PEScope_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.PSO_1_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Unertl8X_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HAMR_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.TA11_4X_Scope");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.VortexSight");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.COMPM4");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Snipex24");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ATACR");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.WaltherMRS_1");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.MZ_UH1");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.WaltherMRS_2");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HD511a_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.CQBR_ACOG_RU");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Carryhandle");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.558holo");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XM157_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Sling
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Sling_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AmmoStraps_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AmmoShellDish_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Recoilpad_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Stock
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.XY_kac");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QT_lugerP80");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QT_F93");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AKSStock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Mk18Stock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QT_LDT416");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QT_Gen3");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.VltorEmod_Blk_Stock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.AK12Stock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.QT_sr");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.CombatOps_Stock_blk");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.HeraCQR_Stock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.TroyM7_Blk");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ViperStock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.MagpulStock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.ar15Stock");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);

-- Stool
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "Gunpart.MZ_HCO");
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 1.5);
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "Gunpart.ArmytekPredator_Bottom1");
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 1.5);
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "Gunpart.ArmytekPredator_Bottom3");
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 1.5);
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "Gunpart.ar15_ddStock");
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Harris_Open");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.Harris_Open1");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M203_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M203_cat_empty");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.GP25_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.GP25_cat_empty");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M28_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.M28_cat_empty");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.bayonet_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.bayonet1_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, "Gunpart.bayonet2_cat");
table.insert(ProceduralDistributions["list"]["LockerArmyBedroomHome"].items, 1.5);