/*
 * Decompiled with CFR 0.152.
 */
package org.lwjgl.system.ffm;

import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.DirectMethodHandleDesc;
import java.lang.constant.DynamicCallSiteDesc;
import java.lang.constant.MethodHandleDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.foreign.StructLayout;
import java.lang.foreign.UnionLayout;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.StringConcatFactory;
import java.lang.invoke.TypeDescriptor;
import java.lang.reflect.Method;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.function.BiPredicate;
import java.util.function.Function;
import java.util.function.ToIntFunction;
import org.lwjgl.system.MemoryUtil;
import org.lwjgl.system.SegmentStack;
import org.lwjgl.system.ffm.FFM;
import org.lwjgl.system.ffm.Group;
import org.lwjgl.system.ffm.GroupBinder;
import org.lwjgl.system.ffm.StackAllocator;
import org.lwjgl.system.ffm.StructBinder;
import org.lwjgl.system.ffm.TraceConsumer;
import org.lwjgl.system.ffm.UnionBinder;
import org.lwjgl.system.ffm.UpcallBinder;

final class BCDescriptors {
    static final ClassDesc CD_AddressLayout = AddressLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Arena = Arena.class.describeConstable().orElseThrow();
    static final ClassDesc CD_BiPredicate = BiPredicate.class.describeConstable().orElseThrow();
    static final ClassDesc CDA_byte = byte[].class.describeConstable().orElseThrow();
    static final ClassDesc CD_Charset = Charset.class.describeConstable().orElseThrow();
    static final ClassDesc CD_FFM = FFM.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Function = Function.class.describeConstable().orElseThrow();
    static final ClassDesc CD_FunctionDescriptor = FunctionDescriptor.class.describeConstable().orElseThrow();
    static final ClassDesc CD_IllegalArgumentException = IllegalArgumentException.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Group = Group.class.describeConstable().orElseThrow();
    static final ClassDesc CD_GroupBinder = GroupBinder.class.describeConstable().orElseThrow();
    static final ClassDesc CD_GroupLayout = GroupLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Linker = Linker.class.describeConstable().orElseThrow();
    static final ClassDesc CD_MemoryLayout = MemoryLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_MemorySegment = MemorySegment.class.describeConstable().orElseThrow();
    static final ClassDesc CD_MemoryUtil = MemoryUtil.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Method = Method.class.describeConstable().orElseThrow();
    static final ClassDesc CD_NullPointerException = NullPointerException.class.describeConstable().orElseThrow();
    static final ClassDesc CD_Record = Record.class.describeConstable().orElseThrow();
    static final ClassDesc CD_SegmentAllocator = SegmentAllocator.class.describeConstable().orElseThrow();
    static final ClassDesc CD_StackAllocator = StackAllocator.class.describeConstable().orElseThrow();
    static final ClassDesc CD_SegmentStack = SegmentStack.class.describeConstable().orElseThrow();
    static final ClassDesc CD_StandardCharsets = StandardCharsets.class.describeConstable().orElseThrow();
    static final ClassDesc CD_StructBinder = StructBinder.class.describeConstable().orElseThrow();
    static final ClassDesc CD_StructLayout = StructLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ToIntFunction = ToIntFunction.class.describeConstable().orElseThrow();
    static final ClassDesc CD_TraceConsumer = TraceConsumer.class.describeConstable().orElseThrow();
    static final ClassDesc CD_UnionBinder = UnionBinder.class.describeConstable().orElseThrow();
    static final ClassDesc CD_UnionLayout = UnionLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_UpcallBinder = UpcallBinder.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ValueLayout = ValueLayout.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ValueLayout$OfByte = ValueLayout.OfByte.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ValueLayout$OfShort = ValueLayout.OfShort.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ValueLayout$OfInt = ValueLayout.OfInt.class.describeConstable().orElseThrow();
    static final ClassDesc CD_ValueLayout$OfLong = ValueLayout.OfLong.class.describeConstable().orElseThrow();
    static final ClassDesc CDA_Linker$Option = Linker.Option.class.describeConstable().orElseThrow().arrayType();
    static final ClassDesc CDA_MethodHandle = ConstantDescs.CD_MethodHandle.arrayType();
    static final ClassDesc CDA_Object = ConstantDescs.CD_Object.arrayType();
    static final ClassDesc CDA_String = ConstantDescs.CD_String.arrayType();
    static final MethodTypeDesc MTD_boolean_Object = MethodTypeDesc.of(ConstantDescs.CD_boolean, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_boolean_Object_Object = MethodTypeDesc.of(ConstantDescs.CD_boolean, ConstantDescs.CD_Object, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_byte_long = MethodTypeDesc.of(ConstantDescs.CD_byte, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_byte_ValueLayout$OfByte_long = MethodTypeDesc.of(ConstantDescs.CD_byte, CD_ValueLayout$OfByte, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_byteArray_Charset = MethodTypeDesc.of(CDA_byte, CD_Charset);
    static final MethodTypeDesc MTD_byteArray_ValueLayout$OfByte = MethodTypeDesc.of(CDA_byte, CD_ValueLayout$OfByte);
    static final MethodTypeDesc MTD_Charset_String = MethodTypeDesc.of(CD_Charset, ConstantDescs.CD_String);
    static final MethodTypeDesc MTD_double_long = MethodTypeDesc.of(ConstantDescs.CD_double, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_float_long = MethodTypeDesc.of(ConstantDescs.CD_float, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_FunctionDescriptor = MethodTypeDesc.of(CD_FunctionDescriptor);
    static final MethodTypeDesc MTD_Group = MethodTypeDesc.of(CD_Group);
    static final MethodTypeDesc MTD_Group_Group = MethodTypeDesc.of(CD_Group, CD_Group);
    static final MethodTypeDesc MTD_Group_MemorySegment = MethodTypeDesc.of(CD_Group, CD_MemorySegment);
    static final MethodTypeDesc MTD_Group_MemorySegment_long = MethodTypeDesc.of(CD_Group, CD_MemorySegment, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_GroupBinder_MemorySegment_Object = MethodTypeDesc.of(CD_GroupBinder, CD_MemorySegment, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_GroupLayout = MethodTypeDesc.of(CD_GroupLayout);
    static final MethodTypeDesc MTD_int = MethodTypeDesc.of(ConstantDescs.CD_int);
    static final MethodTypeDesc MTD_int_long = MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_int_Object = MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_int_ValueLayout$OfInt_long = MethodTypeDesc.of(ConstantDescs.CD_int, CD_ValueLayout$OfInt, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_Linker = MethodTypeDesc.of(CD_Linker);
    static final MethodTypeDesc MTD_Linker_upcallStub = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_MethodHandle, CD_FunctionDescriptor, CD_Arena, CDA_Linker$Option);
    static final MethodTypeDesc MTD_long = MethodTypeDesc.of(ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_long_long = MethodTypeDesc.of(ConstantDescs.CD_long, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_long_Object = MethodTypeDesc.of(ConstantDescs.CD_long, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_long_ValueLayout$OfLong_long = MethodTypeDesc.of(ConstantDescs.CD_long, CD_ValueLayout$OfLong, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_MemoryLayout = MethodTypeDesc.of(CD_MemoryLayout);
    static final MethodTypeDesc MTD_MemorySegment_AddressLayout_long = MethodTypeDesc.of(CD_MemorySegment, CD_AddressLayout, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_MemorySegment_Arena_Object = MethodTypeDesc.of(CD_MemorySegment, CD_Arena, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_MemorySegment_byte = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_byte);
    static final MethodTypeDesc MTD_MemorySegment_long = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_MemorySegment_long_long = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_long, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_MemorySegment_long_MemoryLayout = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_long, CD_MemoryLayout);
    static final MethodTypeDesc MTD_MemorySegment_MemoryLayout_long = MethodTypeDesc.of(CD_MemorySegment, CD_MemoryLayout, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_MemorySegment_MemorySegment = MethodTypeDesc.of(CD_MemorySegment, CD_MemorySegment);
    static final MethodTypeDesc MTD_MemorySegment_MemorySegment_Object = MethodTypeDesc.of(CD_MemorySegment, CD_MemorySegment, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_MemorySegment_Object = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_MemorySegment_String_Charset = MethodTypeDesc.of(CD_MemorySegment, ConstantDescs.CD_String, CD_Charset);
    static final MethodTypeDesc MTD_MethodHandle = MethodTypeDesc.of(ConstantDescs.CD_MethodHandle);
    static final MethodTypeDesc MTD_MethodHandles$Lookup = MethodTypeDesc.of(ConstantDescs.CD_MethodHandles_Lookup);
    static final MethodTypeDesc MTD_MethodHandle_Class_String_MethodType = MethodTypeDesc.of(ConstantDescs.CD_MethodHandle, ConstantDescs.CD_Class, ConstantDescs.CD_String, ConstantDescs.CD_MethodType);
    static final MethodTypeDesc MTD_Object = MethodTypeDesc.of(ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_Object_long = MethodTypeDesc.of(ConstantDescs.CD_Object, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_Object_MemorySegment = MethodTypeDesc.of(ConstantDescs.CD_Object, CD_MemorySegment);
    static final MethodTypeDesc MTD_Object_MemorySegment_long = MethodTypeDesc.of(ConstantDescs.CD_Object, CD_MemorySegment, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_Object_Object = MethodTypeDesc.of(ConstantDescs.CD_Object, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_Object_Object_Object = MethodTypeDesc.of(ConstantDescs.CD_Object, ConstantDescs.CD_Object, ConstantDescs.CD_Object);
    static final MethodTypeDesc MTD_short_long = MethodTypeDesc.of(ConstantDescs.CD_short, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_short_ValueLayout$OfShort_long = MethodTypeDesc.of(ConstantDescs.CD_short, CD_ValueLayout$OfShort, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_StackAllocator = MethodTypeDesc.of(CD_StackAllocator);
    static final MethodTypeDesc MTD_SegmentStack = MethodTypeDesc.of(CD_SegmentStack);
    static final MethodTypeDesc MTD_String = MethodTypeDesc.of(ConstantDescs.CD_String);
    static final MethodTypeDesc MTD_String_long = MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_String_long_Charset = MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_long, CD_Charset);
    static final MethodTypeDesc MTD_String_String = MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_String);
    static final MethodTypeDesc MTD_void_byteArray_Charset = MethodTypeDesc.of(ConstantDescs.CD_void, CDA_byte, CD_Charset);
    static final MethodTypeDesc MTD_void_long = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_void_long_byte = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_byte);
    static final MethodTypeDesc MTD_void_long_short = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_short);
    static final MethodTypeDesc MTD_void_long_int = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_int);
    static final MethodTypeDesc MTD_void_long_long = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_void_long_float = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_float);
    static final MethodTypeDesc MTD_void_long_double = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_double);
    static final MethodTypeDesc MTD_void_long_String_Charset = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_long, ConstantDescs.CD_String, CD_Charset);
    static final MethodTypeDesc MTD_void_MemorySegment_long = MethodTypeDesc.of(ConstantDescs.CD_void, CD_MemorySegment, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_void_Method_Object_ObjectArray = MethodTypeDesc.of(ConstantDescs.CD_void, CD_Method, ConstantDescs.CD_Object, CDA_Object);
    static final MethodTypeDesc MTD_void_String = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_String);
    static final MethodTypeDesc MTD_void_Object_int_MemorySegment_ValueLayout_long_int = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_Object, ConstantDescs.CD_int, CD_MemorySegment, CD_ValueLayout, ConstantDescs.CD_long, ConstantDescs.CD_int);
    static final MethodTypeDesc MTD_void_Throwable = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_Throwable);
    static final MethodTypeDesc MTD_void_ValueLayout$OfByte_long_byte = MethodTypeDesc.of(ConstantDescs.CD_void, CD_ValueLayout$OfByte, ConstantDescs.CD_long, ConstantDescs.CD_byte);
    static final MethodTypeDesc MTD_void_ValueLayout$OfInt_long_int = MethodTypeDesc.of(ConstantDescs.CD_void, CD_ValueLayout$OfInt, ConstantDescs.CD_long, ConstantDescs.CD_int);
    static final MethodTypeDesc MTD_void_ValueLayout$OfShort_long_short = MethodTypeDesc.of(ConstantDescs.CD_void, CD_ValueLayout$OfShort, ConstantDescs.CD_long, ConstantDescs.CD_short);
    static final MethodTypeDesc MTD_void_ValueLayout$OfLong_long_long = MethodTypeDesc.of(ConstantDescs.CD_void, CD_ValueLayout$OfLong, ConstantDescs.CD_long, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_Boolean_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Boolean, ConstantDescs.CD_boolean);
    static final MethodTypeDesc MTD_Byte_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Byte, ConstantDescs.CD_byte);
    static final MethodTypeDesc MTD_Short_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Short, ConstantDescs.CD_short);
    static final MethodTypeDesc MTD_Integer_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Integer, ConstantDescs.CD_int);
    static final MethodTypeDesc MTD_Long_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Long, ConstantDescs.CD_long);
    static final MethodTypeDesc MTD_Float_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Float, ConstantDescs.CD_float);
    static final MethodTypeDesc MTD_Double_valueOf = MethodTypeDesc.of(ConstantDescs.CD_Double, ConstantDescs.CD_double);
    static final DirectMethodHandleDesc DMHD_FFM_bootstrapDowncall = ConstantDescs.ofConstantBootstrap(CD_FFM, "bootstrapDowncall", ConstantDescs.CD_MethodHandle, ConstantDescs.CD_int);
    static final DirectMethodHandleDesc DMHD_StringConcatFactory_makeConcatWithConstants = MethodHandleDesc.ofMethod(DirectMethodHandleDesc.Kind.STATIC, StringConcatFactory.class.describeConstable().orElseThrow(), "makeConcatWithConstants", MethodTypeDesc.of(ConstantDescs.CD_CallSite, ConstantDescs.CD_MethodHandles_Lookup, ConstantDescs.CD_String, ConstantDescs.CD_MethodType, ConstantDescs.CD_String, CDA_Object));
    static final DirectMethodHandleDesc DMHD_GroupBinder_bootstrapRecord = MethodHandleDesc.ofMethod(DirectMethodHandleDesc.Kind.INTERFACE_STATIC, CD_GroupBinder, "bootstrapRecord", MethodTypeDesc.of(ConstantDescs.CD_Object, ConstantDescs.CD_MethodHandles_Lookup, ConstantDescs.CD_String, TypeDescriptor.class.describeConstable().orElseThrow(), ConstantDescs.CD_String, CDA_String));
    static final DynamicCallSiteDesc DCSD_StringConcatFactory_makeConcatWithConstants_AddressToHexString = DynamicCallSiteDesc.of(DMHD_StringConcatFactory_makeConcatWithConstants, "makeConcatWithConstants", MTD_String_String, (ConstantDesc[])new String[]{"0x\u0001"});

    private BCDescriptors() {
    }
}

